### ISSUE TITLE
Cannot open bamfile `sample.clean.bam` (sam: reference already used)

### ISSUE THREAD

**Issue by DieTANG** [tangerzhang/ALLHiC#1]
I was using ALLHiC to deal with a haploid genome. Thus I skip the prune step, but when I run the ALLHiC_partition cmd, I got this error.

**Comment by tangerzhang** [comment]
Could you please post the command lines that you used to generate the bam files?
Also, please indicate the version of samtools you are using. We've tested ALLHiC only on samtools v1.9. Higher version should be OK. But using version 1.3 should be problematic.
