### ISSUE TITLE
assembly a high heterozygous

### ISSUE THREAD

**Issue by yilunhuangyue** [tangerzhang/ALLHiC#10]
Hi, I am assembled a high heterozygous genome. The assembled size is larger than estimated size. Do I need to remove the alternative contigs before using AllHic? 
Thanks for any advices~

**Comment by tangerzhang** [comment]
Yes, remove the heterozygous contigs and then link the non-redundant sequences into one single haplotype to represent the genome of the highly heterozygous genome.
