### ISSUE TITLE
4 different enzymes

### ISSUE THREAD

**Issue by distilledchild** [tangerzhang/ALLHiC#105]
Hi,

I found that ALLHiC support Arima two enzymes that have GATC, GANT, but not support for these four enzymes: ^GATC, G^ANTC, C^TNAG, T^TAA. I read PreprocessSAMs.pl and it merged each enzyme's cutting sites into one , $fasta.near_$RE_site.500.bed. Can I make that file with the same way? 

Thank you.

**Comment by tangerzhang** [comment]
OK, I got it. Yes, you can make it the same way. Good luck!
