### ISSUE TITLE
questions about subsequent processing of allhic assembly results

### ISSUE THREAD

**Issue by caixu0518** [tangerzhang/ALLHiC#11]
Hi, @tanghaibao and @tangerzhang ,

Compared to the reference genome, I found many inversions and other structural errors in the allhic results. I wanted to know if there were any post scripts in your pipelines to correct these errors and detrermined chromosome boundaries?

best,
Xu

**Comment by tangerzhang** [comment]
Hi Xu,
We do not have the post scripts to process these errors. 
These structural errors have to be corrected manually, currently.
