### ISSUE TITLE
How to set RE_site?

### ISSUE THREAD

**Issue by zahngwenda05** [tangerzhang/ALLHiC#113]
Hi,
My enzymes is DnpII, -e parameter should be input “GATC” or "GATCGATC"?  

I check my data 
grep 'GATCGATC' R1.fastq |wc -l
43210413
grep 'GATC' R1.fastq |wc -l
60726348

And I find that in Juicer is 'GATCGATC',
HindIII) ligation="AAGCTAGCTT";;
	DpnII) ligation="GATCGATC";;
	MboI) ligation="GATCGATC";;
	NcoI) ligation="CCATGCATGG";;

could you tell me how to set it best。

By this way ,I find Fastqc‘s report HIC data some warning  ,Do I need to control HIC data,such as  use  Trimmomatic

Thanks for your  reply ！Best wish to you！

**Comment by tangerzhang** [comment]
Hi, for the DnpII or MboI, I used GATC as the input. 
It will be better to control the HiC data and extract reads with high quality.

**Comment by zahngwenda05** [comment]
Ok，I will try it again。thanks！
