### ISSUE TITLE
Parafly线程问题

### ISSUE THREAD

**Issue by Johnsonzcode** [tangerzhang/ALLHiC#118]
尊敬的开发者：
你好! 在运行简单的二倍体挂载pipline时，发现并行的代码是以染色体数目并行的，可能会造成一定的问题，建议修改为$threads。
```
## ALLHiC_pip.sh 104 l
ParaFly -c cmd.list -CPU $group_count
```

**Comment by tangerzhang** [comment]
Thanks for your suggestion! I have modified the code:-)
