### ISSUE TITLE
Allele.ctg.table was none!

### ISSUE THREAD

**Issue by yueyuanliu** [tangerzhang/ALLHiC#13]
I used two draft genome to conduct the command  "blastn" and "blastn_parse.pl", and two *.blast.out files were generated. When  then command "classify.pl", the three files were none, including Allele.ctg.table, remove.log and Allele.gene.table. Can you help me solve this problem?
Another question: If I have new reference genome with long-reads assembly, can I use ALLHIC to assemble hi-c data?
Thanks !

**Comment by tangerzhang** [comment]
Hi Yueyuan,
Could you please share some samples (blast results and two gff3 files) of your data? I would like to check anything wrong in the file format.

**Comment by tangerzhang** [comment]
I am not sure your second question. Did you mean you sequenced and assembled a new genome using long reads, and you would like to use ALLHiC to anchor the assembled contigs into chromosome? If so, the answer is yes. ALLHiC can be applied to a wide range of genome scaffolding based on Hi-C reads, including diploid, allo and autopolypolid genomes. You can try ALLHiC on your data for sure.

**Comment by tangerzhang** [comment]
Problem solved offline
