### ISSUE TITLE
Pruning step after assigning contigs into homologous groups

### ISSUE THREAD

**Issue by Cynthial0l** [tangerzhang/ALLHiC#131]
Hi @tangerzhang,

As you mentioned in https://github.com/tangerzhang/ALLHiC/issues/93, after generating the wrk_dir directory with the script partition_gmap.pl, ALLHiC_prune can be executed individually in each folder with the same Allele.ctg.table.
Following your genome assembly script for sugarcane, I'm a little confused about this command： 
ALLHiC_prune -i Allele.ctg.table -b sample.clean.bam -r seq.fasta.
Should the sample.clean.bam in this command use the prunning.sub.bam generated by partition_gmap.pl or the whole sample.clean.bam previously generated with samtools?

Thanks a lot!

**Comment by kedduck** [comment]
I meet the same problem, could you please share the solution? @Huyuxi08

**Comment by Huyuxi08** [comment]
@kedduck 
Hi, you should use the prunning.sub.bam generated by partition_gmap.pl.

**Comment by kedduck** [comment]
Thanks for your relpy!
