### ISSUE TITLE
Enzyme sites in the tutorial

### ISSUE THREAD

**Issue by Tina9** [tangerzhang/ALLHiC#134]
Hi,

Thanks for developing this useful tool. I am learning how to use it according to the tutorial. However, I have a question about the enzyme sites in the tutorial.

In the step of filtering the sam file in the tutorial, you used MBOI as the enzyme site. The sequence for MBOI is GATC. However, in the partition step in the tutorial, you used HindIII, whose sequence is AAGCTT, as the enzyme site. Could you please tell me the reason? How do we choose the right one in the right step?

![1658028744018](https://user-images.githubusercontent.com/16876314/179382665-14f020ab-9834-4d24-ac8e-2205cbc2c0cf.png)
![1658028772637](https://user-images.githubusercontent.com/16876314/179382678-af587eb5-2bef-40db-a186-2621a88e267a.png)

**Comment by tangerzhang** [comment]
Hi @Tina9 
The enzyme sites in the parameters should be modified according to your Hi-C experiment. If the DNA was digested with MboI, you may use GATC as the enzyme restriction site. Alternatively, it should be AAGCTT if the enzyme was HindIII.

**Comment by Tina9** [comment]
I want to reproduce the analysis of sugarcane in your article. Which one should I use to reproduce your analysis, or should I follow the tutorial on Github and use different restriction sites in different steps?

Many thanks for your reply.

**Comment by tangerzhang** [comment]
Here is the pipeline you can use to reproduce the sugarcane genome scaffolding.
The enzyme was HindIII.

**Comment by Tina9** [comment]
Is there any attachment in your message? Alternatively, you mean the pipeline of wiki on Github. If you mean the pipeline of wiki on Github, what I need to do is to change the cutting sites of the step filtering sam file from MBOI to HindIII, right？

Thanks again for your reply.

**Comment by tangerzhang** [comment]
Here is the link :
https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-an-auto-polyploid-sugarcane-genome

**Comment by Tina9** [comment]
It is so clear. Many thanks for your help.
