### ISSUE TITLE
The algorithm details about the ordering and orientations for contigs

### ISSUE THREAD

**Issue by wlhCNU** [tangerzhang/ALLHiC#14]
hi,
I am very interested in algorithm details about the ordering and orientations for contigs. However the  allhic is a binary code script. I want to get the readable code detail of the binary software to understand how the process of ordering and orientation is implemented. 
I would be very grateful if  I can get your reply.
Thanks.

**Comment by tanghaibao** [comment]
@wlhCNU 

FYI - the source for the binary is [here](https://github.com/tanghaibao/allhic), and contains algorithm detail specifically in `optimize.go`. Paper is coming out soon too with a section on OO.

Haibao

**Comment by wlhCNU** [comment]
Thank you for you response. I still have a question to ask you. In the Tested data directory.  I found the content of draft.asm.fasta file is sam alignment formate. Is there a problem with the content of the file ?
       Thanks

**Comment by tangerzhang** [comment]
Hi @wlhCNU , did you download the test data from the following link (ftp://59.79.232.12/).
I've just checked the draft.asm.fasta. It is fasta format rather than bam alignment. If there is still a problem, I can send you the file through email.

**Comment by wlhCNU** [comment]
Yes, I download the test data from the following link (ftp://59.79.232.12/). The data downloaded this time is correct.  It may be that I made a mistake when I last downloaded the data. Sorry, it has caused you trouble.
Thanks
