### ISSUE TITLE
Can I use the same species'  genome as reference for ALL-HiC haplotype assembly?

### ISSUE THREAD

**Issue by kedduck** [tangerzhang/ALLHiC#140]
Dear developers

Thanks for your ALL-HiC software that make it possible to assemble the haplotypes for polyploid species.

My target species is tetraploid and the chromsome-level reference is available, and I want to assemle the haplotype genome.

I have a question that can I use the same species genome as reference for ALL-HiC haplotype assembly?  

I read the doc about ALL-HiC that reference is used to cluster contigs for the same chromesome and break the HiC signals between alles.

Maybe the question is too simple to answer....

Sorry to disturb you but expect for your rely!

Thanks!

**Comment by tangerzhang** [comment]
Hi @kedduck 
The answer is definitely yes. You can use the genome of the same species as a reference to identify allelic genes.

**Comment by kedduck** [comment]
Very thanks for your rapid solution!
