### ISSUE TITLE
Different chromosomes got different numbers of groups for an autopolyploid genome

### ISSUE THREAD

**Issue by Cynthial0l** [tangerzhang/ALLHiC#142]
Hi, @tangerzhang

I'm trying to use ALLHiC to scaffolding an autopolyploid genome assembled using hifiasm. The coverage of my HiC data is ~150x. First, I used ALLHiC_corrector to correct chimeric contigs, and then I followed your tutorial on scaffolding the auto polyploid sugarcane genome (https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-an-auto-polyploid-sugarcane-genome). After the partition step, I found that different chromosomes got different numbers of groups, such as 1, 5, 10, 19, etc. even though I set k=4. I checked all issues related to this problem and still don't know how to deal with it.

Thanks in advance for any help!

**Comment by wangyibin** [comment]
Hi,
From our experience, the results of partition step were influenced by the abnormal linking signals among contigs. You can adjust the paremeters of `--minREs` and `--maxLinkDensity` in `allhic partition` to control the conditions for filtration, until you obtain groups with reasonable length. For examples:
```
allhic partiiton Chr01.counts_GATC.txt Chr01.pairs.txt 4 --minREs 100 --maxLinkDensity 4
```

**Comment by Cynthial0l** [comment]
Hi, @wangyibin
Thanks a lot. I will have a try.
