### ISSUE TITLE
Is this a HiC scaffolding error?

### ISSUE THREAD

**Issue by Cynthial0l** [tangerzhang/ALLHiC#145]
Hi,

I'm trying to scaffold an autopolyploid genome, and I found an inverted segment on group4 when evaluating through the heatmap. See below.
![0F9145DC-AD91-441F-9693-594F1DC1578B](https://user-images.githubusercontent.com/60483748/200176798-bb181f4f-f9b7-4c35-b80c-f512ad4d8bc9.jpeg)

Then I corrected this segment using Juicebox and got a new heatmap. See below.
![410E3827-2A60-4378-955D-640C6BFB5BE7](https://user-images.githubusercontent.com/60483748/200176814-e8fc8463-7dce-45b1-a3cf-84f71a1ad15b.jpeg)

I don't know if this adjustment is correct. Because I'm not sure if this reversed segment is a HiC scaffolding error or if it reflects a structural variation between different haplotypes of homologous chromosomes. 

Thanks a lot for any help!

**Comment by tangerzhang** [comment]
Hi @Cynthial0l ,
The reversed segment is likely scaffolding errors. And I think they should be corrected ad you did.

**Comment by Cynthial0l** [comment]
Thanks for your kind help!
