### ISSUE TITLE
Strange result of the HiC scaffolding

### ISSUE THREAD

**Issue by Cynthial0l** [tangerzhang/ALLHiC#146]
Hi,

I'm running ALLHiC on an auto-tetraploid genome assembled with hifiasm. I firstly used ALLHiC_corrector to correct chimeric contigs and then used ALLHiC to scaffold them. But the results of each set of homologous chromosome groups are strange, see below. Is this because there are still a large number of chimeric contigs? Or is the effective data of HiC not enough? Could you please give me some advice?

Thanks in advance!
![43A25FD8-2A0A-49C3-A80B-99E19F7F6AA9](https://user-images.githubusercontent.com/60483748/201605357-cac54497-ac4a-4dec-a9ea-9c5ff2d2e118.jpeg)

**Comment by tangerzhang** [comment]
Do you have heatmaps for individual chromosomes? And also please share with me the statistics of Hi-C data, which could be assessed using HiC-Pro.

**Comment by Cynthial0l** [comment]
The heatmap I posted above is the heatmap for eight haplotype groups (four major group) of one chromosome. (I set k=8 in the partition step). And the heatmap of each group of this chromosome is as follows:
![4338C3E4-C0A6-4C82-B475-7B9C48DB5B87](https://user-images.githubusercontent.com/60483748/201643121-bba6edc8-131e-4479-bd4c-634be86183af.jpeg)

The result of my Hi-C data assesed by HiC-Pro is as follows:
![68E830EF-731D-4C81-83A0-89819ADA932E](https://user-images.githubusercontent.com/60483748/201643463-47361f9c-c1e3-4371-8d8b-0a6e084aacfd.png)

**Comment by tangerzhang** [comment]
Hi @Cynthial0l 
It looks like the homologous chromosomes are highly similar as the ratio of uniquely mapped Hi-C reads is only 3.99%, which is likely a major issue to generate a well-presented haplotype-resolved tetraploid assembly. However, it seems that you have assembled four backbones with each representing a haplotype, which can be observed from the whole-genome heatmap. 
To improve this assembly, I would suggest making a synteny dotplot with a reference genome and then manually adjust the assembly using our newly developed tool (https://gitee.com/tanger-lab_enterprise/CATG). The reference genome could be a closely related species, but here you can make a monoploid assembly for your target species.

**Comment by Cynthial0l** [comment]
Hi @tangerzhang

"It looks like the homologous chromosomes are highly similar as the ratio of uniquely mapped Hi-C reads is only 3.99%, which is likely a major issue to generate a well-presented haplotype-resolved tetraploid assembly." 

     Can I increase the unique mapped ratio by increasing the amount of HiC-sequencing data? Because my target species has a heterozygosity of about 0.0343, we still want to get a haplotype-resolved tetraploid assembly. It seems that the CATG tool you mentioned above can only get a monoploid assembly, or I misunderstood.

**Comment by tangerzhang** [comment]
Increasing the amount of Hi-C sequencing data is an alternative approach to improving the assembly. But in the current situation, you can make a synteny analysis with a monoploid reference genome, which can assess the quality of phasing.
The CATG tool is not intended to generate a monoploid assembly, but to adjust the Hi-C-based assembly using a monoploid genome as a reference.

**Comment by Cynthial0l** [comment]
Thanks a lot for your kind help! I will have a try.

**Comment by kedduck** [comment]
> Hi @Cynthial0l It looks like the homologous chromosomes are highly similar as the ratio of uniquely mapped Hi-C reads is only 3.99%, which is likely a major issue to generate a well-presented haplotype-resolved tetraploid assembly. However, it seems that you have assembled four backbones with each representing a haplotype, which can be observed from the whole-genome heatmap. To improve this assembly, I would suggest making a synteny dotplot with a reference genome and then manually adjust the assembly using our newly developed tool (https://gitee.com/tanger-lab_enterprise/CATG). The reference genome could be a closely related species, but here you can make a monoploid assembly for your target species.

Hi @tangerzhang 
Thanks for your software CATG and I have Download it. 

When I run python ./CATG.py, the screen reports "TypeError: int() argument must be a string, a bytes-like object or a number, not 'KeyboardModifier'"

How can I to run the pragram?
