### ISSUE TITLE
How to generate the user-prepared.clusters.txt in the Global rescue step efficiently?

### ISSUE THREAD

**Issue by wu116** [tangerzhang/ALLHiC#148]
Dear developers,

Thank for your software and careful manual. I just used ALLHiC to assemble haplotype genome with an allotetraploid geome from same species, and it worked fluently until I tried to work on global rescue.

There are about 4748 contigs after using ALLHiC_corrector, and only 2000 contigs have been assigned to pre-set groups. I tried to rescue those lost contigs, but I have no idea how to generate the user-prepared.clusters.txt. Could you please introduce some detailed method that you have used?

And I have the germ of an idea: can I use the .clm file to cluster lost contigs into pre-set groups by calculating and comparing the average distance between them? If this way is worked, could you please explain how the .clm file show the ordering and orientation between contigs(especially the ordering)?

Thanks a lot!

**Comment by Yujiaxin419** [comment]
Hello,

### How to prepare '.clusters.txt'
For the first question, about how to generate user-prepared.clusters.txt, there is a solution:
```bash
## If you start with an .agp file
Thanks for using ALLHiC!

For the first question, about how to generate user-prepared.clusters.txt, there is a solution:
```bash
agp="path to agp"
grep -v '#' ${agp} | egrep 'Chr|chromosome|chr|Chromosome|group' \
    |cut -f 1 |sort -u|while read chrID;do
    ctgNum=`grep -w ${chrID} ${agp} | grep 'W' |wc -l`;
    ctg=`grep -w ${chrID} ${agp} | grep -w  'W' | cut -f 6 | tr '\n' ' '`;
    echo -e "${chrID}\t${ctgNum}\t${ctg}" >> clusters.txt;
    done

## If you start with a series of pre-set groups file. (File names should be :group???.txt or counts_RE.??g???.txt)
### In this case, I assume file names are: prunning.counts_AAGCTT.8g?.txt
ls  prunning.counts_AAGCTT.8g?.txt |while read filename;do
    chrID=`basename ${filename/.txt}`;
    ctgNum=`sed 1d ${filename} | wc -l`;
    ctg=`sed 1d ${filename} | cut -f 1 | tr '\n' '\t'`;
    echo -e "${chrID}\t${ctgNum}\t${ctg}" >> clusters.txt;
    done
```
--------------------
### Introduce .clm file
In order to discuss the second question, we should discuss the '.clm' format at first.

-  '.clm' is a 4-column file. It contains contig pair, Interaction number and interaction distances in different orientation. For example:
``` bash
# contigA  contigB      Interaction number      Interation distances
utgA+ utgB+    7       137414 142833 164125 209815 211156 211156 316650
utgA+ utgB-    7       78857 110323 195010 233694 233694 294409 318526
utgA- utgB+    7       37474 61591 122306 122306 160990 245677 277143
utgA- utgB-    7       39350 144844 144844 146185 191875 213167 218586
```
- The distance between an interaction record is:
> refererence: [ALLHiC extract](https://github.com/tanghaibao/allhic/blob/1a79c6ea1a3d66725037827e896b8e5c23d6dbc1/extract.go)
```bash
#             read1                                           read2
#	---a-- X|----- dist = a2 ----|         |--- dist = b ---|X ------ b2 ------
#       ==============================         ====================================
#             C1 (length L1)         |----D----|         C2 (length L2)

# For C1+ C2+
distance = a2 + b
# For C1+ C2-
distance = a2 + b2
# For C1- C2+
distance = a + b
# For C1- C2-
distance = a + b2
```
### Order and Orientation determined algorithm of ALLHiC
through parsing .clm file, ALLHiC is able to determine the order and orientation between contigs within a group, respectively.
> Reference: [ALLHiC paper](https://www.nature.com/articles/s41477-019-0487-8#Sec15)
- For order:
ALLHiC defined an object function, and maximum the _**S**_ through genetic algorithm:
$$S = \mathop {\sum}\limits_{i,j \in {\mathrm{contigs}}} {\frac{{L\left( {i,j} \right)}}{{D\left( {i,j} \right)}}}$$
> where _L(i,j)_ is the number of Hi-C links between contigs _i_ and _j_, and _D(i,j)_ is the distance (in bp) between the mid-points of these two contigs. 

Obviously, the larger the _**S**_ score, the more the links between adjacent contig pairs, which is consistent with the principle that Hi-C tends to interact proximal. So that the order of contig set can be determined.

- For orientation:
ALLHiC defined a different object function, and maximum the _**P**_ through a greedy method:
$$P = \mathop {\sum }\limits_{i,j \in {\rm{contigs}}}\, \mathop {\sum}\limits_{k \in {\rm{all}}\,{\rm{links}}\,{\rm{{between}}}\,i\,{\rm{and}}\,j} {\frac{1}{{d_k}}}$$
> where _dk_ is the distance of the two ends of a Hi-C link between contigs _i_ and _j_. Note that this distance varies depending on the relative orientation between contigs _i_ and _j_, up to four distinct values (_i_+|_j_+, _i_+|_j_–, _i_–|_j_+, _i_–|_j_–). The scoring function _**P**_ is then simply the sum of the reciprocal of the link distance.

When the _**P**_ score improves, the links within a contig pair are closer. This also is consistent with the principle that Hi-C tends to interact proximal. 

### For global rescue with '.clm' file
At the end, performing global rescue with .clm file is a good idea, but I think using '.pairs.txt' file will be easier.  '.pairs.txt' file is based on '.clm' file and it record observed links and expected links between contig pairs.  We can cluster lost contigs into pre-set groups by comparing observed links between them.

```bash
## The '.pairs.txt' file looks like:
#X      Y       Contig1 Contig2 RE1     RE2     ObservedLinks   ExpectedLinksIfAdjacent Label
0       1       utg001021l_1532000_1669999      utg002484l_514000_699999        39      75      12      871.4   ok
0       44      utg001021l_1532000_1669999      utg002590l_411000_574999        39      55      4       803.1   ok
0       45      utg001021l_1532000_1669999      utg003102l_1_96999      39      32      5       565.8   ok
0       52      utg001021l_1532000_1669999      utg000599l_1_455999     39      152     17      1498.2  ok
```

Hope discussion above is helpful!

Yujiaxin

**Comment by wu116** [comment]
Thank you so much for your prompt reply! I spent lots of time to learn from your reply and gained a lot about how ALLHiC work.

But I still get a bit confuse about global rescue with '.pairs.txt' file. For example:
```
##Links of contig bctg3 in the '.pairs.txt':
##bctg3 is a lost contig
#X      Y       Contig1 Contig2 RE1     RE2     ObservedLinks   ExpectedLinksIfAdjacent Label
0	3	bctg0	bctg3	558	4	5	4.7	ok
3	4	bctg3	bctg4	4	190	4	3.4	ok
3	1509	bctg3	bctg1059	28120	3	14.8	ok
```

To figure out which groups that bctg3 should be, first I select the pairs which meet 1. `ObservedLinks > ExpectedLinksIfAdjacent`; 2. Number of `ObservedLinks - ExpectedLinksIfAdjacent` is biggest, and I get:
```
#X      Y       Contig1 Contig2 RE1     RE2     ObservedLinks   ExpectedLinksIfAdjacent Label
3	4	bctg3	bctg4	4	190	4	3.4	ok
```

Then, I grep bctg4 in the groups.agp file of each homologous group and find it in the homologous group Chr05, pre-set group2. (My speices: (2n=4x=40)).So I edit the prunning.clusters.txt:
```
#prunning.clusters.txt **before** editing
#Group	nContigs	Contigs
2g2	38	bctg... bctg4 bctg...
```
```
#prunning.clusters.txt **after** editing
#Group	nContigs	Contigs
2g2	39	bctg... bctg3 bctg4 bctg...
```
After editing all the prunning.clusters.txt in every homologous group, I generate the user-prepared.clusters.txt by combining all the prunning.clusters.txt and use it to run global rescue:
```
#user-prepared.clusters.txt
#Group	nContigs	Contigs
40g1	...
...
40g10	39	bctg... bctg3 bctg4 bctg...
...
40g40	...
```

I still work on it so I haven't got the results yet, but I just want to know if my understanding and the steps of performing global rescue are correct or not, could you please help me check it out?

Thanks for your kind again!!

**Comment by Yujiaxin419** [comment]
Hi,

I think the steps of you performing global rescue are right, but I haven't tested this method. I'm looking forward to your results.

Additionally, Check the un-anchor contig and editing the clusters.txt file manually is time-consuming. Is there an easier way to perform global rescue? Or we can just use ALLHiC_rescue directly, I think it should be work for your situation.

All the best,
Yujiaxin

**Comment by wu116** [comment]
Thanks a million!!! I get your point finally! 

What your mean is that we do not need to cluster the un-anchor contigs into user-prepared.clusters.txt during global rescue, the ALLHiC_rescue will achieve this goal automatically just like what it has done in the pipeline. Am I right?

I made a little modify on your script for merging the clusters.txt files into one, and it seems work in my case!
```
cd wrk_dir
find * -maxdepth 0|while read line;do
agp=$line/groups.agp
grep -v '#' ${agp} | grep 'group' \
    |cut -f 1 |sort -u|while read chrID;do
    ctgNum=`grep -w ${chrID} ${agp} | grep 'W' |wc -l`;
    ctg=`grep -w ${chrID} ${agp} | grep -w  'W' | cut -f 6 | tr '\n' ' '`;
    chrID=`echo ${chrID}|sed 's/group//g'`
    echo -e "${line}_${chrID}\t${ctgNum}\t${ctg}" >> clusters.txt;
    done
done
```
The final clusters.txt can be used in global rescue and I get a perfect result. I think cluster the lost contigs manually maybe is in vain if we just want to cluster instead of correcting.

Thank you so much again!!!

**Comment by Yujiaxin419** [comment]
You're welcome. It has been my pleasure helping you out! 

Yes, you're right. That is what I mean. ALLHiC_rescue can generate a series of new groups.txt files, then we can get a new cluster file.

Hope you get a good assembly result.
