### ISSUE TITLE
GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by SaiReddy-A** [tangerzhang/ALLHiC#149]
Hi,
I followed the installation but when I tried to run `ALLHiC_prune -h` I got the following error..
### ALLHiC_prune: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ALLHiC_prune)

I checked the `/lib64/libstdc++.so.6` using `strings /lib64/libstdc++.so.6|grep 'GLIBCXX_3.4.21'` but GLIBCXX_3.4.21 is not there. However, I checked a different location of gcc library where  GLIBCXX_3.4.21  does exist, but I'm not sure how to proceed next..

I'm on a cluster with no sudo privileges, could you please look into it.

Thanks!!

**Comment by wyim-pgl** [comment]
Install Conda.

create allhic environment
```
conda create -n allhic
conda activate allhic
mamba install -c omgarcia gcc-6
mamba install -c bioconda matlock samtools chromap bedtools
```
Install Allhic from Wiki

Load GlibcXX
```
export LD_LIBRARY_PATH=$(readlink -f $(which chromap) | sed 's/bin\/chromap/gcc6\/lib/g'):$LD_LIBRARY_PATH
ldd ALLHiC_prune

ALLHiC_prune -h
```
