### ISSUE TITLE
Can we creat .hic and .assembly files by using  groups.agp and groups.asm.fasta ?

### ISSUE THREAD

**Issue by wlhCNU** [tangerzhang/ALLHiC#17]
hi,
   In the end of  Build analysis, we will get both groups.agp and groups.asm.fasta. Is it possible for us to generate .hic and  .assembly files which are the input files for JuiceBox software ? If we can creat these files, then we can load .hic and .assembly files to further correct possible assembly errors by Juicebox Assembly Tools.
Thanks

**Comment by tangerzhang** [comment]
OK, we may spend some time to figure out how those files (.hic and .assembly) format, but we can not commit when the code will be available.

**Comment by tangerzhang** [comment]
The PhaseGenomics has provided codes to get .hic and .assembly files that can be directly used for juicebox adjustment. Please find the codes from the following link:
https://github.com/phasegenomics/juicebox_scripts
