### ISSUE TITLE
Write 0 partitions to `input.clusters.txt`

### ISSUE THREAD

**Issue by zilaijuand** [tangerzhang/ALLHiC#172]
Thank you for developing f ALLHIC. When I use ALLHiC_partition function, no results were generated. Is something wrong?  Looking forward to your help, thank you.
Extract function: calculate an empirical distribution of Hi-C link size based on intra-contig links
CMD: allhic extract input.bam asiatica.latest.fasta --RE GATC
14:31:11 writeRE | NOTICE  RE counts in 332 contigs (total: 2832130, avg 1 per 310 bp) written to `input.counts_GATC.txt`
14:31:11 extractContigLinks | NOTICE  Parse bamfile `input.bam`
14:31:48 extractContigLinks | NOTICE  Extracted 38 intra-contig link groups (total = 2340700)
14:31:52 extractContigLinks | NOTICE  Extracted 2555 inter-contig groups to `input.clm` (total = 7847688, maxLinks = 21675, minLinks = 3)
14:31:52 fitPowerLaw | NOTICE  Power law Y = 4.15e-05 * X ^ -0.8490
14:31:52 writeDistribution | NOTICE  Link size distribution written to `input.distribution.txt`
14:31:52 readClmLines | NOTICE  Parse clmfile `input.clm`
14:31:54 calcInterContigs | NOTICE  Contig pair analyses written to `input.pairs.txt`
14:31:54 Run | NOTICE  Success
Partition contigs based on prunning bam file
CMD: allhic partition input.counts_GATC.txt input.pairs.txt 19 --minREs 25
14:31:54 ReadCSVLines | NOTICE  Parse csvfile `input.counts_GATC.txt`
14:31:54 readRE | NOTICE  Loaded 332 contig RE lengths for normalization from `input.counts_GATC.txt`
14:31:54 skipContigsWithFewREs | NOTICE  skipContigsWithFewREs with MinREs = 25 (RE = GATC)
14:31:54 skipContigsWithFewREs | NOTICE  Marked 0 contigs (avg 0.0 RE sites, len 0) since they contain too few REs (MinREs = 25)
14:31:54 ReadCSVLines | NOTICE  Parse csvfile `input.pairs.txt`
14:31:54 skipRepeats | NOTICE  skipRepeats with multiplicity = 2
Contig #0 (ptg000001l) has 5.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #1 (ptg000002l) has 5.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #2 (ptg000003l) has 5.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #3 (ptg000004l) has 15.8x the average number of Hi-C links -> MARKED REPETITIVE
Contig #4 (ptg000005l) has 4.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #5 (ptg000006l) has 4.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #6 (ptg000007l) has 4.5x the average number of Hi-C links -> MARKED REPETITIVE
Contig #7 (ptg000008l) has 4.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #8 (ptg000009l) has 4.7x the average number of Hi-C links -> MARKED REPETITIVE
Contig #10 (ptg000011l) has 5.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #11 (ptg000012l) has 3.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #12 (ptg000013l) has 6.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #13 (ptg000014l) has 4.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #14 (ptg000015l) has 5.5x the average number of Hi-C links -> MARKED REPETITIVE
Contig #16 (ptg000017l) has 4.8x the average number of Hi-C links -> MARKED REPETITIVE
Contig #17 (ptg000018l) has 5.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #18 (ptg000019l) has 15.0x the average number of Hi-C links -> MARKED REPETITIVE
Contig #19 (ptg000020l) has 4.7x the average number of Hi-C links -> MARKED REPETITIVE
Contig #20 (ptg000021l) has 4.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #21 (ptg000022l) has 4.5x the average number of Hi-C links -> MARKED REPETITIVE
Contig #26 (ptg000027l) has 3.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #27 (ptg000028l) has 2.8x the average number of Hi-C links -> MARKED REPETITIVE
Contig #28 (ptg000029l) has 3.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #30 (ptg000031c) has 23.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #32 (ptg000033l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #35 (ptg000036l) has 2.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #39 (ptg000040l) has 8.5x the average number of Hi-C links -> MARKED REPETITIVE
Contig #42 (ptg000043l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #49 (ptg000050l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #52 (ptg000053l) has 16.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #57 (ptg000058l) has 2.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #58 (ptg000059l) has 2.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #59 (ptg000060l) has 2.3x the average number of Hi-C links -> MARKED REPETITIVE
Contig #62 (ptg000063l) has 2.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #63 (ptg000064c) has 2.7x the average number of Hi-C links -> MARKED REPETITIVE
Contig #75 (ptg000076l) has 8.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #86 (ptg000087l) has 2.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #88 (ptg000089l) has 5.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #90 (ptg000091l) has 13.5x the average number of Hi-C links -> MARKED REPETITIVE
Contig #101 (ptg000102l) has 2.3x the average number of Hi-C links -> MARKED REPETITIVE
Contig #119 (ptg000120l) has 2.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #134 (ptg000135l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #138 (ptg000139l) has 2.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #149 (ptg000150l) has 2.7x the average number of Hi-C links -> MARKED REPETITIVE
Contig #151 (ptg000152l) has 3.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #153 (ptg000154l) has 18.0x the average number of Hi-C links -> MARKED REPETITIVE
Contig #180 (ptg000181l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #182 (ptg000183l) has 4.7x the average number of Hi-C links -> MARKED REPETITIVE
Contig #203 (ptg000204l) has 6.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #206 (ptg000207l) has 2.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #215 (ptg000216l) has 2.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #216 (ptg000217l) has 18.6x the average number of Hi-C links -> MARKED REPETITIVE
Contig #223 (ptg000224l) has 2.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #244 (ptg000245l) has 2.1x the average number of Hi-C links -> MARKED REPETITIVE
Contig #246 (ptg000247l) has 2.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #255 (ptg000256l) has 2.2x the average number of Hi-C links -> MARKED REPETITIVE
Contig #273 (ptg000274l) has 2.9x the average number of Hi-C links -> MARKED REPETITIVE
Contig #299 (ptg000300l) has 5.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #330 (ptg000331l) has 2.4x the average number of Hi-C links -> MARKED REPETITIVE
Contig #331 (ptg000332l) has 2.2x the average number of Hi-C links -> MARKED REPETITIVE
14:31:54 skipRepeats | NOTICE  Marked 60 contigs (avg len 14410944) as repetitive (MaxLinkDensity = 2)
14:31:54 Cluster | NOTICE  Clustering starts with 332 (272 informative) contigs with target of 19 clusters
14:31:54 Cluster | NOTICE  No more merges to do since the queue is empty
14:31:54 setClusters | NOTICE  setClusters summary (NonInformativeRatio = 3): nPassRatio = 0, nFailRatio = 0, nFailCluster=60
14:31:54 printClusters | NOTICE  Write 0 partitions to `input.clusters.txt`
14:31:54 Run | NOTICE  Success

**Comment by zilaijuand** [comment]
The data may have errors.

**Comment by zilaijuand** [comment]
Sorry, we exclude the sequence issue and the error are still there.

**Comment by pramodpantha** [comment]
I'm having the exact same issue, did you solve the problem?

**Comment by xujialupaoli** [comment]
I will also encounter the same situation, not output any partitions.
[ALLHiC_partition.log](https://github.com/tangerzhang/ALLHiC/files/14537061/ALLHiC_partition.log)
[ALLHiC_partition_err.log](https://github.com/tangerzhang/ALLHiC/files/14537062/ALLHiC_partition_err.log)

**Comment by lunky-zao** [comment]
I'm having the same issue, did you solve the problem?
