### ISSUE TITLE
ALLHiC on diploid draft genome questions

### ISSUE THREAD

**Issue by rpwang** [tangerzhang/ALLHiC#18]
Hi,

Hi,

Iam currently using ALLHiC on a diploid draft assembly. I have a two questions though:
1) The number of pre defined groups (k) in the ALLHiC partition is the same as the number of chromosomes in the genome? So for example 12 chromosomes, k=12 or is it 2n: k=24?
2) I also see the number of single copies in BUSCO results has increased in the  ALLHiC scaffolded assembly compared to the draft assembly. I expected the change to be minimal. Is this normal?

**Comment by tangerzhang** [comment]
For Q1, If the diploid genome has 24 chromosomes (2n=2x=24) and you would like to assemble 12 chromosomes, the K value should be 12. For example, Arabidopsis genome has 10 chromosomes and it is a diploid. Assembly of the genome will return one set of haplotype, including only 5 chromosomes. Therefore, K should be 5.
For Q2, it is not normal. ALLHiC will not change contig sequences actually and therefore should not influence BUSCO results.

**Comment by rpwang** [comment]
Thanks for the answers. For Q2 I had thoughts..going to check what went wrong!
