### ISSUE TITLE
Rescue stage:   Use of uninitialized value in concatenation (.) or string at /bin/ALLHiC/bin/ALLHiC_rescue line 165.

### ISSUE THREAD

**Issue by rpwang** [tangerzhang/ALLHiC#20]
Hi, I am running ALLHiC on a polyploid genome. Everything went fine till  at the rescue stage a few perl messages like these showed up:

Number of original contigs in contig000650: 0
Number of rescued contigs in contig000650: 1
Use of uninitialized value in concatenation (.) or string at /bin/ALLHiC/bin/ALLHiC_rescue line 165.
Use of uninitialized value in concatenation (.) or string at /bin/ALLHiC/bin/ALLHiC_rescue line 165.
Number of original contigs in group3: 822
    
According the help and the git instructions I used the correct files. I rechecked what I have done at the prunn and partition stages and the input files were correct. 

Any tips?

**Comment by tangerzhang** [comment]
[ALLHiC_rescue.zip](https://github.com/tangerzhang/ALLHiC/files/3566362/ALLHiC_rescue.zip)
Could you please test the attached rescue version?

**Comment by rpwang** [comment]
It worked! No perl messages. Thanks!
