### ISSUE TITLE
Dose the tool produces full length haplotypes ?

### ISSUE THREAD

**Issue by bd904** [tangerzhang/ALLHiC#21]
Hi,
I was wondering if this tool produces the full length haplotypes with the common reagon in each fasta file produced or it just gives the fasta for sequences that are uncommon between the haplotypes.

**Comment by tangerzhang** [comment]
Hi,
We aimed to produce the full length sequences for each haplotype, including not only common sequences but also variants among homologous chromosomes. Therefore, ALLHiC expects contig level assembly as many as possible.

**Comment by bd904** [comment]
Okay,
Thanks a lot!!
