### ISSUE TITLE
Are there other methods to speed up the 'bwa sampe' step?

### ISSUE THREAD

**Issue by WTarabidopsis** [tangerzhang/ALLHiC#22]
Hi, 
Thanks for sharing this program. I was trying to use ALLHiC to help with my genome assembly, however, the first step `Map Hi-C reads to draft assembly` ran almost one week and still not finished. I found that the bottleneck was `bwa sampe`, it has run 5 days and generated `.sam` file slowly. Is that OK? Are there other efficient ways to speed up this step?

Best,
WTarabi

**Comment by tangerzhang** [comment]
One alternative way to speed up the mapping precess is to split fastq files into small pieces and run each PE reads individually. After that, merge the clean bam files.

**Comment by Rachel-pku** [comment]
hi,after spliting  fastq data to speed up the step of bwa sampe, I am wondering transferring  to bam files or filtting the sam files first.because of samtools merge is special for bam files.thanks a lot. What is worse, when i use PreprocessSAMs.pl, the output files has no meaningful content. something is wrong with my script. i don't know how to solve it.

**Comment by tangerzhang** [comment]
Hi @Rachel-pku , you can use the command ```cat *.filter.sam > sample.clean.sam && samtools view -bt draft.asm.fasta.fai sample.clean.sam > sample.clean.bam``` to merge sam files and convert the sam file to bam file.
For the PreprocessSAMs.pl output, could you please share log file or a couple of lines of its output. I will check what happened.

**Comment by Rachel-pku** [comment]
Thanks for your reply，this is log file. 

"my" variable $RE_site masks earlier declaration in same scope at /appsnew/bioapps/LACHESIS/bin/PreprocessSAMs.pl line 44.
Sun Feb 16 12:49:05 2020: PreprocessSAMs.pl: samtools view -bS pilon2_dbg4_next4_part_001.sam -o pilon2_dbg4_next4_part_001.bam
/appsnew/bioapps/LACHESIS/bin/PreprocessSAMs.pl pilon2_dbg4_next4_part_001.sam ../pilon2_dbg4_next4.fasta DPNII

Sun Feb 16 12:49:35 2020: PreprocessSAMs.pl: bedtools intersect -abam pilon2_dbg4_next4_part_001.bam -b ../pilon2_dbg4_next4.fasta.near_DPNII.500.bed > pilon2_dbg4_next4_part_001.REduced.bam
Sun Feb 16 12:49:48 2020: PreprocessSAMs.pl: samtools view -F12 pilon2_dbg4_next4_part_001.REduced.bam -b -o pilon2_dbg4_next4_part_001.REduced.paired_only.bam
Sun Feb 16 12:49:48 2020: PreprocessSAMs.pl: samtools flagstat pilon2_dbg4_next4_part_001.REduced.paired_only.bam > pilon2_dbg4_next4_part_001.REduced.paired_only.flagstat

**Comment by tangerzhang** [comment]
@Rachel-pku 
It seems that you were using the script ```PreprocessSAMs.pl``` from LACHESIS package rather than that from ALLHiC.
Actually, I have modified this script and archived it in ALLHiC package. Could you please switch it and try it again? The right one can be found here: https://github.com/tangerzhang/ALLHiC/blob/master/scripts/PreprocessSAMs.pl

**Comment by Rachel-pku** [comment]
sorry for my mistake. I use the script in ALLHiC package,but there also have errors: **Unable to open file ../pilon1_dbg4_necat4.fasta.near_.500.bed. Exiting**. My script :PreprocessSAMs.pl pilon1_dbg4_necat4_part_001.sam ../pilon1_dbg4_necat4.fasta DPNII. 
Mon Feb 17 19:32:52 2020: PreprocessSAMs.pl: samtools view -bS pilon1_dbg4_necat4_part_001.sam -o pilon1_dbg4_necat4_part_001.bam
[W::sam_read1] Parse error at line 1049065
[main_samview] truncated file.
Use of uninitialized value $RE_site in concatenation (.) or string at /lustre1/bin/ALLHiC/scripts/PreprocessSAMs.pl line 134.
Use of uninitialized value $RE_site in concatenation (.) or string at /lustre1/bin/ALLHiC/scripts/PreprocessSAMs.pl line 135.
/lustre1/bin/ALLHiC/scripts/PreprocessSAMs.pl pilon1_dbg4_necat4_part_001.sam ../pilon1_dbg4_necat4.fasta DPNII

Mon Feb 17 19:33:01 2020: PreprocessSAMs.pl: make_bed_around_RE_site.pl ../pilon1_dbg4_necat4.fasta  500

make_bed_around_RE_site.pl

Find all occurrences of a motif in a genome.  Make a 'POS' file listing these occurrences, and also a BED file representing the regions around these occurrences.

SYNTAX: make_bed_around_RE_site.pl <fasta> <motif> <range>
fasta:  A fasta file representing a genome (reference or draft assembly.)
motif:  A motif, typically a restriction site sequence (e.g., HindIII = AAGCTT, NcoI = CCATGG, Dpn1 = GATC).
range:  A number representing how many bp around the sequence to include.  Recommend 500 based on Yaffe & Tanay, Nat. Genetics 2011.

OUTPUT FILES:
<fasta>.near_<motif>.<range>.bed
<fasta>.near_pos_of_<motif>.txt

Mon Feb 17 19:33:01 2020: PreprocessSAMs.pl: bedtools intersect -abam pilon1_dbg4_necat4_part_001.bam -b ../pilon1_dbg4_necat4.fasta.near_.500.bed > pilon1_dbg4_necat4_part_001.REduced.bam
Error: Unable to open file ../pilon1_dbg4_necat4.fasta.near_.500.bed. Exiting.

**Comment by Rachel-pku** [comment]
Another question. the **raw data** used  for mapping is  duplication removed data from sequence company.

**Comment by tangerzhang** [comment]
Hi @Rachel-pku 
Sorry for the late response. I am not able to access my gmail and github during last days. Please send me email (tanger_009@163.com) or add my QQ (418632423) if you still need my assistance.
Based on the error log file you provided, I assume that the script ```make_bed_around_RE_site.pl``` could not find a bed which recored restriction sites. This file should be generated in your working path by the same script. You can try the following command lines to solve this problem:
```
ln -s ../pilon1_dbg4_necat4.fasta ./
PreprocessSAMs.pl pilon1_dbg4_necat4_part_001.sam pilon1_dbg4_necat4.fasta GATC
```

For the second question, there will be no problem to remove the duplicated reads as they are not informative in ALLHiC scaffolding.
