### ISSUE TITLE
Died at ALLHiC/bin/ALLHiC_build line 12

### ISSUE THREAD

**Issue by wangzhennan14** [tangerzhang/ALLHiC#24]
Hi,
    When I use ALLHIC to assembly a draft genome, there was an error as follow:
    1. tour format to agp ...
    Died at /ALLHiC/bin/ALLHiC_build line 12.
    I followed this https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-of-a-simple-diploid-genome.
    Could you help me to solve this? Thank you very much!
wangzhennan

**Comment by xioxiu** [comment]
I met the same problem. Would you tell me how you solve the problem?

**Comment by xioxiu** [comment]
您好，你的来信已收到，我会尽快给你回复。

**Comment by xioxiu** [comment]
Thank you very much!
I just figured it out




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangerzhang/ALLHiC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangerzhang/ALLHiC] Died at ALLHiC/bin/ALLHiC_build line 12 (#24)





 
Hi @xioxiu
 ALLHiC_build requires that all of the tour files should be placed in the working directory.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
