### ISSUE TITLE
Length mismatch after Pilon

### ISSUE THREAD

**Issue by wyim-pgl** [tangerzhang/ALLHiC#28]
Dear Xingtan,
After I ran Pilon for error correction, I found some error like this.
Look like allhic extraction cannot read my fasta length. Do you have any solutions?
![image](https://user-images.githubusercontent.com/907041/69325573-39a67e00-0bff-11ea-887d-513a728e0b6e.png)

Thanks.

**Comment by tangerzhang** [comment]
Hi Won,
It seams that you are using different reference genomes in the bam file (a.bam) and input fasta file (canu.illumina.fasta).
I know the length of sequences in your assembly will be changed after running pilon polishing. Could you please use the assembly before running Pilon? Please let us know if this does not solve the problem.

**Comment by plantgenomicslab** [comment]
Yes I made a mistake to select reference. By the way, will you come over to see me next January?

**Comment by tangerzhang** [comment]
I am afraid I am not going to PAG 2020 as the Chinese New Year will come early next year. I will stay with my family in the vocation. 
Hope you guys have fun :-)

**Comment by wyim-pgl** [comment]
Oh no 🙉

-------------------------------
Won Cheol Yim, Ph.D
Assistant Professor
Department of Biochemistry & Molecular Biology
University of Nevada – Reno
MS330 1664 N. Virginia Street
Reno NV 89557
Cell: +1-775-229-0453
Fax: 775-784-1419
Email: wyim@unr.edu
http://www.plantbioinformatics.org
________________________________
