### ISSUE TITLE
Globally rescue: format of user-prepared.clusters.txt -

### ISSUE THREAD

**Issue by diriano** [tangerzhang/ALLHiC#34]
Could you please elaborate on the format of the user-prepared.clusters.txt file to carry out the globally rescue step?
thanks,
Diego

**Comment by tangerzhang** [comment]
Hi Diego,
Here is the description of ALLHiC_rescue and the clusters.txt format can be found in github (https://github.com/tangerzhang/ALLHiC/wiki) as well
![image](https://user-images.githubusercontent.com/6403754/72962223-b36d0a80-3dee-11ea-862d-bccf6694452b.png)
