### ISSUE TITLE
Something wrong about "Optimize" steps

### ISSUE THREAD

**Issue by Yang-Tui** [tangerzhang/ALLHiC#36]
Hello,
Thanks for this great Hic pipeline. A month ago, I had some trouble of the spending too much time for "Optimize" steps. And you suggested to check the data format, command lines and log file whether there is any error reported. And I rerun it,  but it still spent cpu time over 400 hours, and it is still working!!!

So I wondered if the HiC contacts too low let it work so long? Or maybe just my Hi-C quality is too bad.

 
It's my Hi-C date after juicer.
```
 Sequenced Read Pairs:  441,811,039
 Normal Paired: 199,286,377 (45.11%)
 Chimeric Paired: 25,363,801 (5.74%)
 Chimeric Ambiguous: 153,132,631 (34.66%)
 Unmapped: 64,028,230 (14.49%)
 Ligation Motif Present: 174,921,480 (39.59%)
Alignable (Normal+Chimeric Paired): 224,650,178 (50.85%)
Unique Reads: 62,625,023 (14.17%)
PCR Duplicates: 161,848,665 (36.63%)
Optical Duplicates: 176,490 (0.04%)

Library Complexity Estimate: 64,629,613
Intra-fragment Reads: 21,622,234 (4.89% / 34.53%)
Below MAPQ Threshold: 17,483,057 (3.96% / 27.92%)
Hi-C Contacts: 23,519,732 (5.32% / 37.56%)
 Ligation Motif Present: 5,254,662  (1.19% / 8.39%)
 3' Bias (Long Range): 67% - 33%
 Pair Type %(L-I-O-R): 25% - 27% - 24% - 24%
Inter-chromosomal: 5,968,399  (1.35% / 9.53%)
Intra-chromosomal: 17,551,333  (3.97% / 28.03%)
Short Range (<20Kb): 17,151,373  (3.88% / 27.39%)
Long Range (>20Kb): 399,954  (0.09% / 0.64%)
```

Thank you so much.

**Comment by tanghaibao** [comment]
@Yang-Tui 

Would you please send the last portion of your log file? I am wondering if the optimize step is stuck in some sort of infinite loop.

Thanks,
Haibao

**Comment by Yang-Tui** [comment]
@tanghaibao 
Attached is the output file.
I skip many lines, because it is stuck in the infinite loop as you mention.
And yes, it repeats these two lines ........
So, we never completed in this step. 


```
ESC[32m10:44:16 flipLog | NOTICE ESC[0m FLIPWHOLE: -440.85561 => -440.85561 ACCEPT
ESC[32m10:44:16 flipOne | NOTICE ESC[0m FLIPONE: N_accepts=0 N_rejects=3
```


Thank you.


[allhic_out.txt](https://github.com/tangerzhang/ALLHiC/files/4169520/allhic_out.txt)

**Comment by tanghaibao** [comment]
@Yang-Tui 

Yes, this is a [bug](https://github.com/tanghaibao/allhic/issues/11) in a previous version which should have fixed. Can you print the version of your `allhic` binary?

```console
./allhic --version
```

Make sure you are using the latest binary in the repo.

Haibao

**Comment by Yang-Tui** [comment]
@tanghaibao 

`ALLHIC version 0.8.12`

OK, I will update allhic.v0.9.8 (It is the new version, right?).

Thanks for your help.

**Comment by tanghaibao** [comment]
@Yang-Tui 

Yes, that should fix this issue. Please report back if the problem stays.

Haibao

**Comment by Yang-Tui** [comment]
@tanghaibao 
I remove ALLhic and reinstall by using` git clone https://github.com/tangerzhang/ALLHiC`

And the file `allhic.v0.9.8` is in the ALLHic fold definitely.

But using `allhic --version`, it shows `ALLHIC version 0.8.12`.

So I am confused, so which version exactly I'm using?

Is there a bug for print the old version but I am using  allhic.v0.9.8 ???

Thanks.

**Comment by tangerzhang** [comment]
@Yang-Tui 
The program ```allhic``` in bin/ folder is still old version and I am sorry I have  not updates that.
Please replace bin/allhic with allhic.v0.9.8 using the following command line:
```
cp allhic.v0.9.8 bin/allhic
chmod +x bin/allhic
```

**Comment by Yang-Tui** [comment]
@tanghaibao @tangerzhang 

Thanks to both of you, after using the `allhic.v0.9.8`, the problem is solved.
