### ISSUE TITLE
allhic prune.pl fail

### ISSUE THREAD

**Issue by MichelMoser** [tangerzhang/ALLHiC#37]
Hi, 

I would like to test all-hic and am stuck at the pruning step using the command: 

```
ALLHiC/scripts/prune.pl -i Allele.ctg.table -b bam.files.txt -r Simon_Salmon.flye15K_pilon.fasta
```

I get files remove.log, removedb_Allele.txt and removedb_nonBest.txt created but afterwards, the command dies saying there is no prunning.bam. Indeed, there is no such file, as it was never created. 
The code to create is commented out in the prune.pl script. 

I am missing something in the ALLHiC pipeline? 

Cheers, 
Michel

**Comment by tangerzhang** [comment]
The script ```prune.pl``` used another script ```remove_reads.pl``` to filter reads. 
Please make sure the script ```remove_reads.pl``` located in your environment path.
Alternatively you can modify line 119 in ```prune.pl```  script and add absolute path for the script ```remove_reads.pl```.

**Comment by MichelMoser** [comment]
ah, i just saw the error. script `move_reads.pl` expects bam names in a file called `bam.list` as input. 
renaming the bam fofn into `bam.list` solved the problem.
