### ISSUE TITLE
Allele.ctg.table for genome with no annotation

### ISSUE THREAD

**Issue by pezhmansafdari** [tangerzhang/ALLHiC#38]
Hi,

I have a fresh highly polymorphic denovo assembly and I am not planning on doing annotation before I phase the genome. Is there a way to create Allele.ctg.table without annotation (CDS and GFF3) files? 

BR,
Pezhman

**Comment by tangerzhang** [comment]
Yes, here is an alternative approach to generate the Allele.ctg.table without annotation:
https://github.com/tangerzhang/ALLHiC/issues/16

**Comment by pezhmansafdari** [comment]
Thanks
