### ISSUE TITLE
Can I use scaffold-level draft assembly for ALLHic?

### ISSUE THREAD

**Issue by hungweichen0327** [tangerzhang/ALLHiC#39]
Dear community,

I understand the input of original draft assembly for ALLHic scaffolding is contig-level. I am curious that is it possible to use scaffold-level assembly as input data? I have one draft assembly used Flye assembler which have 223 contigs (N50 = 12 Mb) and estimated genome size is 500 Mb. This assembler also provide scaffolding process to order contigs into scaffolds based on the repeat graph structure. And I got assembly of 193 fragments after scaffolding process by Flye (30 scaffolds and 163 contigs, and there 100 Ns in the gap in each scaffold).
So, can I use 193 fragments to do scaffolding by ALLHic? Or is there any advise that I can do?
Thank you for the help.

**Comment by tangerzhang** [comment]
Hi @hungweichen0327 
It is possible to use scaffolds as input of draft assembly. However, our experience indicates that ALLHiC is very sensitive to the quality of input assembly. Usually, the scaffolds are highly  continuous but contain many mis-assembly errors. This will lead chimeric assembly in ALLHiC. Therefore, I would recommend the contig level assembly with high-quality (i.e. avoiding chimeric/mis-assembled contigs as many as possible).

**Comment by hungweichen0327** [comment]
Dear Dr. @tangerzhang,
Thank you for the quick reply and suggestion. I will use contig-level assembly.
