### ISSUE TITLE
bwa mem

### ISSUE THREAD

**Issue by Lordhooze** [tangerzhang/ALLHiC#4]
can I use bwa mem instead of bwa aln?
align reads to the genome?

**Comment by tangerzhang** [comment]
BWA mem was not fully supported, especially when running filterBAM_forHiC.pl
To speed up bwa aln, I usually split the fastq files to small pieces and run reads mapping individually.

**Comment by Rachel-pku** [comment]
Hi, tangerzhang. After splitting the fastq files to small pieces and run reads mapping individually, merging the bam files or  filtting sam files first (enzyme site)?
