### ISSUE TITLE
download testdata problem

### ISSUE THREAD

**Issue by shiyi-pan** [tangerzhang/ALLHiC#40]
hi,I can't invite the host 59.79.232.12,can you give me a favor.here is my method:
I used the filezilla to connect the host.I set the host as ftp://59.79.232.12/ and username as AllHiCData and password as allhic and port as 21.

**Comment by tangerzhang** [comment]
Here is an alternative link from Baidu Cloud to download tested data:
https://pan.baidu.com/s/1caryNh_7tC9GLRdHCWbvDQ  
password: hgfl
Our server (59.79.232.12) has been working more than 6 years and I am sure it needs a good rest.

**Comment by shiyi-pan** [comment]
thank you for your help

**Comment by shiyi-pan** [comment]
hi,Thank you for your reply, I have downloaded the test data and found no raw hic data in it , is't convenient for you to give me a download ULR so that I can learn how to use allhic from start to finish?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tanger Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 晚上8:51
收件人:&nbsp;"tangerzhang/ALLHiC"<ALLHiC@noreply.github.com&gt;;
抄送:&nbsp;"梦"<1343213784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tangerzhang/ALLHiC] download testdata problem (#40)




Here is an alternative link from Baidu Cloud to download tested data:
 https://pan.baidu.com/s/1caryNh_7tC9GLRdHCWbvDQ
 password: hgfl
 Our server (59.79.232.12) has been working more than 6 years and I am sure it needs a good rest.

**Comment by tangerzhang** [comment]
Hi @shiyi-pan 
The test data starts from four basic functions of ALLHiC, that are prune, partition, optimize and build.
If you want to start from hic reads mapping, you can download the sugarcane hic reads we released in gsa (https://bigd.big.ac.cn/gsa/browse/CRA001597) and assembly from UIUC server (http://www.life.illinois.edu/ming/downloads/Spontaneum_genome/). Since the assembly is chromosomal level rather than contig level, you can use the attached script (convert_HiCAsm_to_Ctg.py) to convert chromosomes into contigs, which can be used as a reference. And if you would like to start from scratch, I suggest you can follow the details from this link (https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-an-auto-polyploid-sugarcane-genome).
[convert_HiCAsm_to_Ctg.py.TXT](https://github.com/tangerzhang/ALLHiC/files/4312432/convert_HiCAsm_to_Ctg.py.TXT)

**Comment by shiyi-pan** [comment]
hi,Tanger Zhang,thank you vrey much . I notice the ALLHiC need an&nbsp;Allele.gene.table, in your github there is an method to generate the file and the method need  gff3 file.can you tell me the speice of test data so I can generate the Allele.gene.table file?

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tanger Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 晚上8:38
收件人:&nbsp;"tangerzhang/ALLHiC"<ALLHiC@noreply.github.com&gt;;
抄送:&nbsp;"梦"<1343213784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tangerzhang/ALLHiC] download testdata problem (#40)




Hi @shiyi-pan
 The test data starts from four basic functions of ALLHiC, that are prune, partition, optimize and build.
 If you want to start from hic reads mapping, you can download the sugarcane hic reads we released in gsa (https://bigd.big.ac.cn/gsa/browse/CRA001597) and assembly from UIUC server (http://www.life.illinois.edu/ming/downloads/Spontaneum_genome/). Since the assembly is chromosomal level rather than contig level, you can use the attached script (convert_HiCAsm_to_Ctg.py) to convert chromosomes into contigs, which can be used as a reference. And if you would like to start from scratch, I suggest you can follow the details from this link (https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-an-auto-polyploid-sugarcane-genome).
 convert_HiCAsm_to_Ctg.py.TXT

**Comment by tangerzhang** [comment]
We used sorghum as the diploid reference genome to generate Allele.gene.table and Allele.ctg.table. I am sure it will be helpful if you have time to read our publications in Nature Plants (https://www.nature.com/articles/s41477-019-0487-8)

**Comment by shiyi-pan** [comment]
ok,thank you for your help .
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tanger Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 晚上8:59
收件人:&nbsp;"tangerzhang/ALLHiC"<ALLHiC@noreply.github.com&gt;;
抄送:&nbsp;"梦"<1343213784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tangerzhang/ALLHiC] download testdata problem (#40)




We used sorghum as the diploid reference genome to generate Allele.gene.table and Allele.ctg.table. I am sure it will be helpful if you have time to read our publications in Nature Plants (https://www.nature.com/articles/s41477-019-0487-8)
