### ISSUE TITLE
assembly workflow using falcon-phase output and ALLHiC

### ISSUE THREAD

**Issue by Jennie17** [tangerzhang/ALLHiC#41]
Hi, @tanghaibao and @tangerzhang ,

Thanks for developing ALLHiC, a tool in urgent need and handy to use.

From your expertise, could you please kindly provide some advice about my assembly workflow?

I am doing a genome assembly (two separate nuclei in one cell and each nucleus with a set of chromosomes) and my aim is to generate a chromosome-level assembly which is fully phased. So I am actually expecting 2 fasta assembly files, each for one nucleus.

Now I have phased.0.fa and phased.1.fa for the diploid genome generated by falcon-phase, and hic data, and I am wondering what's the best approach to get the final 2 fasta assembly files for each nucleus?

Shall I just use phased.0.fa for 3d-dna for misjoin correction, then allhic for scaffolding and do the same thing for phased.1.fa separately?

My concern is that for phased.0.fa,  although each contig is fully phased (which means all bases within the contig come from one nucleus), two contigs may come from two different nuclei. 
Same problem for phased.1.fa.
So if I used phased.0.fa and phased.1.fa separately, I won't be able to get chromosome sequence fully phased.

To get 2 fasta assembly files, each for one nucleus, I have the following questions.

1. Then maybe it's better/possible to concatenate phased.0.fa and phased.1.fa together and do 3d-dna misjoin correction and allhic?
 
2. Will 3d-dna work for concatenated two copies of genome? If so, in such a situation,  what would be the recommended parameter settings for 3d-dna that can go well with downstream allhic?

3. Then for allhic, is a Allele.ctg.table is required since we have two copies in the input now?

Looking forward to your advice

Best wishes

Jeannie

**Comment by tangerzhang** [comment]
Hi @Jennie17 
Below are my response to your questions:
1. Yes. It will be better to merge phased.0.fa and phased.1.fa and then use the merged fasta file as input of 3D-DNA.
2. I usually use 3D-DNA with default parameters to correct the contigs.
3. Yes. In your case, you will need Allele.ctg.table to prune the bam files.

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Many thanks for your immediate reply.

for step 3, will ALLHiC be able to output 2 assembly fasta files for each nucleus? Or it will only generate one copy of assembly fasta file?

Any parameter to be able to get 2 fasta assembly files, each for one nucleus?

**Comment by tangerzhang** [comment]
Hi @Jennie17 , 
No, ALLHiC will not output two fasta assembles. Actually, it will generate only one assembly, containing all of chromosomes. You will need to determine which two chromosomes are homologous.
I think I will be not possible to fully partition the assembly into different nucleus. Because you never know which chromosomes are from nucleus A and which from B. For instance, I assume that you can assemble all of the chromosomes (let's suppose it is 10 and each nucleus has 5) and you label two homologous chromosomes as A and B. You will find Chr1A and Chr1B are homologous chromosomes but you do not know whether Chr1A and Chr2A (or Chr2B) are from the same nucleus. Am I right?

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Thanks for your clarification.

Yes, you are right.

For example, if each nucleus has 5 chromosomes, the ALLHiC will output all 10 chromosomes as one assembly.

Another thing to confirm is that for my situation, the input is merged phased.0 and phased.1 fasta files and after 3d-dna correction, I may eventually get one file "tig.HiCcorrected.fasta" as input for ALLHiC as previously suggested.

 Assume each nucleus has 5 chromosomes, for this input file, I shall set k = 5 or k = 10?

If I don't merge phased.0 and phased.1, just use one of them to get through to the final 3d-dna output, in this case, shall I set k = 5 or k = 10?

**Comment by Jennie17** [comment]
Hi @tangerzhang 

Your discussion about phasing is quite good.

Just one more point.

As you mentioned:
"You will find Chr1A and Chr1B are homologous chromosomes but you do not know whether Chr1A and Chr2A (or Chr2B) are from the same nucleus."

I fully agree that you won't know whether Chr1A with Chr2A or with Chr2B is from the same nucleus.

I just want to confirm that as we went through from the very beginning with merged pahsed.0 and phased.1, so the Chr1A generated from ALLHiC will contain DNA sequences from the actual one chromosome, not part from Chr1A, part from Chr1B.  That means, the sequences within the chromosome are fully/correctly phased. Is my understanding correct?

**Comment by tangerzhang** [comment]
> Hi @tangerzhang,
> 
> Thanks for your clarification.
> 
> Yes, you are right.
> 
> For example, if each nucleus has 5 chromosomes, the ALLHiC will output all 10 chromosomes as one assembly.
> 
> Another thing to confirm is that for my situation, the input is merged phased.0 and phased.1 fasta files and after 3d-dna correction, I may eventually get one file "tig.HiCcorrected.fasta" as input for ALLHiC as previously suggested.
> 
> Assume each nucleus has 5 chromosomes, for this input file, I shall set k = 5 or k = 10?
> 
> If I don't merge phased.0 and phased.1, just use one of them to get through to the final 3d-dna output, in this case, shall I set k = 5 or k = 10?

If your input assembly contains sequences from two nucleus (i.e. merged file), K value should be 10 or even larger. This is because sometimes ALLHiC is not able to get the ideal number of groups as ALLHiC is sensitive to the contig level assembly. We have a discussion regarding factors that may have influence on ALLHiC results in our NP paper. This may be helpful to understand the results you are going to have.
If the input assembly only contains sequences from one nucleus, K should be 5.

**Comment by tangerzhang** [comment]
> Hi @tangerzhang
> 
> Your discussion about phasing is quite good.
> 
> Just one more point.
> 
> As you mentioned:
> "You will find Chr1A and Chr1B are homologous chromosomes but you do not know whether Chr1A and Chr2A (or Chr2B) are from the same nucleus."
> 
> I fully agree that you won't know whether Chr1A with Chr2A or with Chr2B is from the same nucleus.
> 
> I just want to confirm that as we went through from the very beginning with merged pahsed.0 and phased.1, so the Chr1A generated from ALLHiC will contain DNA sequences from the actual one chromosome, not part from Chr1A, part from Chr1B. That means, the sequences within the chromosome are fully/correctly phased. Is my understanding correct?

Not exactly. That depends on what degree your contig level assembly is accurate. Are you sure that one contig in FALCON-phase assembly is absolutely from one specific nucleus? Based on my experience, the current assemblers usually mess up contigs and generate a large proportion of chimeric contigs. That means one contig may contain sequences from both nucleus (i.e. part from Chr1A and Chr1B). Based on the situation, we may not expect that one ALLHiC group is from one actual chromosome.  
Our simulation shows that ALLHiC is very sensitive to proportion of chimeric contigs and it only can tolerate 5% of chimeric contigs. That's why I recommend you to use 3D-DNA to correct the mis-joint contigs. Even though, it is still very changeling to phase two haplotypes. This is really a hard work.

**Comment by Jennie17** [comment]
Hi @tangerzhang,

I've got the seq.FINAL.fasta from 3d-dna and I am trying to use your script to convert to the input for ALLHiC.
 
I have a couple of questions.

1. For the command:
perl /scratch/WLR6411/jingqinwuhome/tools/ALLHiC/scripts/release3DDNA.pl No_of_chr seq.FINAL.fasta

What does the "No_of_chr " here refers to?

Is it a) the total number of "cat seq.FINAL.fasta | grep '^>' | wc -l " 
OR b) the total number of my original assembly fasta as input for 3d-dna processing (cat my.original.asm.fasta | grep '^>' | wc -l ) 
OR c) the expected/guessed chr number/k values for my genome (e.g., each nucleus has 5 chromosomes,  my input is concatenated phased.0 and phased.1.fasta, and my k = 10), so the "No_of_chr"=10 ?

2. About the 3d-dna output
I found that the seq.FINAL.fasta is much more fragmented than my original input.

My original concatenated input has about 340 contigs, after running 3d-dna, the seq.FINAL.fasta gets about 1972 fragments in the final fasta. 

I used "-m diploid" as my input has concatenated fasta sequences from both nuclei.

Is there something wrong?  Will this affect allHiC final results?

What could be done to improve?

Thanks!

**Comment by tangerzhang** [comment]
No_of_chr is the expected number of chromosomes. Yes, it is 10 in the case we assumed before. My script ```release3DDNA.pl``` has two functions:
1) Since 3D-DNA only output a list of scaffolds and did not indicate which ones are chromosomes, this script will select the top longest N scaffolds as chromosomes (N is No_of_chr). This will be helpful in simple diploid genome assembly, such as Arabidopsis and rice, but not in highly heterozygous and polyploid genome assemblies like the genome you are working.
2) It will split 'split.FINAL.fasta' by gaps (i.e. N) and the resulting contig file is Hi-C corrected contigs that can be used as input of ALLHiC.
No worry about the fragmented output of 3D-DNA. This may indicate that there are many chimeric contigs in the initial contig assembly. We only use 'tig.HiCcorrected.fasta' as input of ALLLHiC and I would like to know the statistics of this file.

**Comment by Jennie17** [comment]
@tangerzhang 

What exactly statistics of 'tig.HiCcorrected.fasta' you want to know?

**Comment by Jennie17** [comment]
Hi @tangerzhang,

I also used your gmap script to generate the allelic contig table.

qry=target.genome  # 你的多倍体序列
ref_cds=reference.cds.fasta # 同源物种的cds
N=4 #你的基因组倍性, 4表示的是4倍体
gmap_build -D . -d DB $qry
gmap -D . -d DB -t 12 -f 2 -n $N  $ref_cds > gmap.gff3

perl gmap2AlleleTable.pl referenece.gff3

My Question:
For the last command "perl gmap2AlleleTable.pl referenece.gff3", I think the "referenece.gff3" actually refers to the generated "gmap.gff3" from the command "gmap -D . -d DB -t 12 -f 2 -n $N  $ref_cds > gmap.gff3"?

**Comment by tangerzhang** [comment]
> @tangerzhang
> 
> What exactly statistics of 'tig.HiCcorrected.fasta' you want to know?

You can get the statistics using this PERL script: 
https://github.com/tangerzhang/my_script/blob/master/faSize.pl

**Comment by tangerzhang** [comment]
> Hi @tangerzhang,
> 
> I also used your gmap script to generate the allelic contig table.
> 
> qry=target.genome # 你的多倍体序列
> ref_cds=reference.cds.fasta # 同源物种的cds
> N=4 #你的基因组倍性, 4表示的是4倍体
> gmap_build -D . -d DB $qry
> gmap -D . -d DB -t 12 -f 2 -n $N $ref_cds > gmap.gff3
> 
> perl gmap2AlleleTable.pl referenece.gff3
> 
> My Question:
> For the last command "perl gmap2AlleleTable.pl referenece.gff3", I think the "referenece.gff3" actually refers to the generated "gmap.gff3" from the command "gmap -D . -d DB -t 12 -f 2 -n $N $ref_cds > gmap.gff3"?

No. The file 'reference.gff3' is from a diploid reference genome rather than gmap.gff3. For instance, we were working on sugarcane genome, which is an auto-tetraploid genome. Then we used sorghum genome as a reference to generate Allele.ctg.table. The reference.gff3 file is annotation of diploid sorghum genome, collected from phytozome.

**Comment by Jennie17** [comment]
Hi @tangerzhang 

Thanks for the clarification.

I am a bit confused.

So reference.gff3 comes from the same genome of reference.cds.fasta.

But then what's the use of generated gmap.gff3 generated from "gmap -D . -d DB -t 12 -f 2 -n $N $ref_cds > gmap.gff3"?

It haven't been used at all after generation?

**Comment by tangerzhang** [comment]
If you look into the codes of this script ```gmap2AlleleTable.pl```, you will find this script reads 'gmap.gff3' automatically.

**Comment by Jennie17** [comment]
Hi @tangerzhang, 

When using  gmap2AlleleTable.pl, why I keep on having this error message?

Use of uninitialized value $gene in substitution (s///) at tools/ALLHiC/scripts/gmap2AlleleTable.pl line 20, <IN> line 28500.
Use of uninitialized value $gene in exists at tools/ALLHiC/scripts/gmap2AlleleTable.pl line 21, <IN> line 28500.

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Will the problem lie in the format of my files shown as below? 

$ head myReference.transcripts.fa  (i.e., reference.cds.fasta)                                                             

">GN64P176_000001                                                                                               
ATGGTCAGCATGTACCTCCAATCGTTGCATCACGCCCCAGGAAACCCTCAATTAGGACACAGTCAAGATGA..."
">GN64P176_000002
ATGTCACGGACCATACTCAAGGTTCGAGAGGCTGGAGATCCAAGCCTCTTCCTCATCCTGCAATCTACCATC..."

$ head gmap.gff3                                                                                               
##gff-version   3                                                                                              
000000F_1       DB      gene    25070   25690   .       +       .       ID=GN64P176_000004.path1;Name=GN64P176_000004           
000000F_1       DB      mRNA    25070   25690   .       +       .       ID=GN64P176_000004.mrna1;Name=GN64P176_000004;Parent=GN64P176_000004.path1;coverage=100.0;identity=100.0;matches=621;mismatches=0;indels=0;unknowns=0                                                                                                                 
000000F_1       DB      exon    25070   25690   100     +       .       ID=GN64P176_000004.mrna1.exon1;Name=GN64P176_000004;Parent=GN64P176_000004.mrna1;Target=GN64P176_000004 621 1 .      

$ head myReference.gff3                                                                     
##gff-version 3                                                                                          
000000F EVM     gene    1549    2498    .       -       .       ID=GN64P176_000001                       
000000F EVM     mRNA    1549    2498    .       -       .       ID=GN64P176_000001-T1;Parent=GN64P176_000001
000000F EVM     exon    1549    1767    .       -       .       ID=evm.model.000000F.1.exon3;Parent=GN64P176_000001-T1
000000F EVM     exon    1791    2243    .       -       .       ID=evm.model.000000F.1.exon2;Parent=GN64P176_000001-T1
000000F EVM     exon    2310    2498    .       -       .       ID=evm.model.000000F.1.exon1;Parent=GN64P176_000001-T1
000000F EVM     CDS     1549    1767    .       -       0       ID=cds.evm.model.000000F.1;Parent=GN64P176_000001-T1

**Comment by Jennie17** [comment]
Hi @tangerzhang,

After reading your code, I think the bug is in the "myReference.gff3".

This gff3 has "ID=", but your code expect "Name", so I sed 's/ID=/Name=/g' myReference.gff3, then the bug disappear.

Have I got it right?

**Comment by tangerzhang** [comment]
> Hi @tangerzhang,
> 
> After reading your code, I think the bug is in the "myReference.gff3".
> 
> This gff3 has "ID=", but your code expect "Name", so I sed 's/ID=/Name=/g' myReference.gff3, then the bug disappear.
> 
> Have I got it right?

Yes, you are right. You can modify the code and make it to read ```ID=```.

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Thanks for your confirmation.

After I set k = 40 (assume one nucleus 20 chr, 2 nuclei has k=40), the final length in bp for each group as below.

5 groups are really small (120-700 kb), one at the end is extremely large (56 Mb).

I don't know the real chromosome number, 20 is my guess based on relevant species.

According to this output, do you recommend me to set k smaller or larger for further optimization?

What would you recommend for incremental step, e.g., k = 20, 30, 40 ...? or k=20, 22, 24, 26...

Group length in bp:
120347                                                   
377398                                                   
432156                                                   
522419                                                   
690311                                                   
1190256                                                  
2170758                                                  
2534348
2881035
3417374
3526426
3591473
4155116
4219220
4378032
4696829
4720440
4721106
4927249
5040383
5142058
5185375
5286590
5594168
5654376
5698908
5966002
6398687
6471416
6731367
6998151
7392829
7532763
9585687
10725994
11165302
11989701
12560880
14159733
56808444

**Comment by tangerzhang** [comment]
You can try K=20, 40, 80, 120. Then use dotplot analysis to find which groups are chimeric and need to be splited manually.

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Thanks for your suggestion.

I'd like to email you the dotplot figures for the different k values to ask for your advice.

Could you please tell me your email?

Thanks!

**Comment by Jennie17** [comment]
Hi @tangerzhang,

Looking at the chr length below, does it mean K=120 is better than k=20?

When you look at 500k_whole_genome.pdf and 500k_all_chrs.pdf generated from your script, what are the major aspects to look at/compare so that I can tell which k is better?

For k=20, chr length listed as below, there is one group extremely large, 85 Mb.
120347
690311
794596
4969400
5040383
5594859
7116536
7232404
7353337
7573949
9735053
10832575
11210307
12726606
14015570
14159733
15014010
16728007
29299616
85155508

For k=120, the extremely large chr seems to disappear and sizes seem to be more even, but about 20 groups under 1 Mb.
120347                                                                                                                   
291493                                                                                                                   
292974                                                                                                                   
350689                                                                                                                   
362181                                                                                                                   
377398                                                                                                                   
432156                                                                                                                   
464412                                                                                                                   
522355                                                                                                                   
527676                                                                                                                   
558405                                                                                                                   
706255                                                                                                                   
753001                                                                                                                   
775700                                                                                                                   
834136                                                                                                                   
869327                                                                                                                   
873152                                                                                                                   
881717                                                                                                                   
954820                                                                                                                   
987941                                                                                                                   
1012314                                                                                                                  
1048847                                                                                                                  
1087279                                                                                                                  
1088903                                                                                                                  
1104535                                                                                                                  
1114826                                                                                                                  
1141732                                                                                                                  
1145898                                                                                                                  
1181634                                                                                                                  
1185362                                                                                                                  
1209943                                                                                                                  
1232832                                                                                                                  
1249678                                                                                                                  
1287179                                                                                                                  
1291528                                                                                                                  
1300895                                                                                                                  
1375525                                                                                                                  
1376586                                                                                                                  
1433791                                                                                                                  
1452961                                                                                                                  
1476427                                                                                                                  
1488785                                                                                                                  
1513334                                                                                                                  
1515842                                                                                                                  
1551377                                                                                                                  
1583197                                                                                                                  
1585842                                                                                                                  
1685545                                                                                                                  
1690078                                                                                                                  
1699221                                                                                                                  
1699371                                                                                                                  
1711469                                                                                                                  
1734911                                                                                                                  
1769762                                                                                                                  
1776400                                                                                                                  
1851032                                                                                                                  
1855017                                                                                                                  
1865353                                                                                                                  
1876366                                                                                                                  
1914088                                                                                                                  
1920334                                                                                                                  
1926187                                                                                                                  
1942170                                                                                                                  
1988583                                                                                                                  
2003301                                                                                                                  
2029355                                                                                                                  
2070128                                                                                                                  
2080074                                                                                                                  
2169273
2170758
2242755
2342650
2437099
2512100
2534952
2571506
2612244
2651994
2719880
2750308
2792320
2797234
2813816
2818731
2851586
2859756
2903909
2907932
2931577
2933786
2984512
3003875
3005740
3006582
3022351
3058457
3139376
3205178
3207672
3342733
3410507
3567128
3574288
3632661
3715457
3749267
3785068
3789447
3798456
3934281
3966029
4025011
4030637
4221079
4455387
5059175
5907146
6216837
7515173
7636389

**Comment by tangerzhang** [comment]
> Hi @tangerzhang,
> 
> Thanks for your suggestion.
> 
> I'd like to email you the dotplot figures for the different k values to ask for your advice.
> 
> Could you please tell me your email?
> 
> Thanks!

Here is my email:
tanger_009@163.com

**Comment by Rachel-pku** [comment]
hi, tangerzhang,
After using  juicer + 3d-dna + release3DDNA.pl, I got tig.HiCcorrected.fasta and groups.asm.fasta, because of your perl scrips include ALLHIC_build. How can I get the plot?

**Comment by tangerzhang** [comment]
> hi, tangerzhang,
> After using juicer + 3d-dna + release3DDNA.pl, I got tig.HiCcorrected.fasta and groups.asm.fasta, because of your perl scrips include ALLHIC_build. How can I get the plot?

Hi @Rachel-pku, 
In the step after you running 3d-dna, you can still use the output file ".hic" to visualize the heapmaps.
Alternatively, you can use the following steps to generate plot but this requires re-mapping reads to the assembly:
1. re-mapping Hi-C reads to groups.asm.fasta
2. use the script to generate a HiC heatmap (https://github.com/tangerzhang/ALLHiC/blob/master/scripts/bam_HiCplotter.py):
```
python bam_HiCplotter.py mapping.bam chrn.list 150k pdf
```
chrn.list records chromosome names in the first column and chromosome lengths in the second column.
