### ISSUE TITLE
enzyme_sites problem

### ISSUE THREAD

**Issue by baishengjun** [tangerzhang/ALLHiC#42]
Hi，
In Filtering SAM file step : PreprocessSAMs.pl sample.bwa_aln.sam draft.asm.fasta MBOI; you use MBOI enzyme.
but in Partition step : ALLHiC_partition -b prunning.bam -r draft.asm.fasta -e AAGCTT -k 16; why you use -e AAGCTT parameter. 
 I have some errors when I follow your command; and I use -e GATC parameter ,it worked.
but in last result,it seems some mistakes in group15 and group16.
![Uploading image.png…]()

**Comment by tangerzhang** [comment]
Hi @baishengjun 
I am not able to open the picture you posted and thus not sure what the error it is?
In the example commands, you can just modify the enzyme parameter according to your experiment.
If you still need my assistance, please post the error message or send it to my email: tanger_009@163.com
