### ISSUE TITLE
Dnase as enzyme parameter

### ISSUE THREAD

**Issue by KevinBredemeyer** [tangerzhang/ALLHiC#43]
Hello,
I was wondering if ALLHiC supports libraries generated using DNASE as the fragmenting enzyme?
If so, what should be input for the enzyme parameters during the filtering and partitioning step of the pipeline?
Thanks,
Kevin

**Comment by tangerzhang** [comment]
In theory, the input enzyme should be anything the user provided. You can just use the restriction sites as input for ALLHiC, e.g. GATC

**Comment by KevinBredemeyer** [comment]
Dnase cuts randomly and therefore does not have a set restriction site. 
Are you suggesting I use GATC as a stand-in input?
Thanks!
K

**Comment by tangerzhang** [comment]
Hi Kevin,
When we analyze the HiC data, we usually extracted reads that are located in the  500 bp flanking regions of any restriction site. If the Dnase cuts randomly, the HiC assemblers (e.g. ALLHiC or 3DDNA) can not determine which reads should be used and which should be discarded. I am afraid that ALLHiC is not supported libraries generated using Dnase enzyme. Sorry for the negative answer.
