### ISSUE TITLE
can the results of sample.bwa_aln.REduced.paired_only.flagstat normal?

### ISSUE THREAD

**Issue by wuxiaopei0509** [tangerzhang/ALLHiC#46]
the results of samtools flagstat sample.bwa_aln.REduced.paired_only.bam that is sample.bwa_aln.REduced.paired_only.flagstat as follows,the "19691 + 0 properly paired (0.01% : N/A)"
![图片](https://user-images.githubusercontent.com/52643750/84747285-a47b3480-afe9-11ea-83ba-efd5ffc86c2d.png)
is this results normally for subsequent analysis?
Thank you!

**Comment by tangerzhang** [comment]
I think this is abnormal. I've checked one of my bam files from a polyploid genome and it shows 30% properly paired.

**Comment by wuxiaopei0509** [comment]
Thank you.But the reason is what ? At this case ,I used the contig assembly. The process is normal at a scaffold level assembly .
Thank you!

**Comment by tangerzhang** [comment]
Sorry for that I have no idea why it happened.
