### ISSUE TITLE
What should I do with low heterozygous and diploid genome？

### ISSUE THREAD

**Issue by DustinChen1986** [tangerzhang/ALLHiC#47]
I have a low heterozygous and diploid insect genome of about 480m. I notice ALLHIC is nearly the only  HIC assembly tool maintained well. So I want to try ALLHIC to finish my assembly. The question is what I should do with this issue , just follow the WIKI or skip the Prune step?

**Comment by DustinChen1986** [comment]
Sorry. I think I find the answer.
https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-of-a-simple-diploid-genome

**Comment by tangerzhang** [comment]
Good to know you found the solution :-)
