### ISSUE TITLE
problems with allhic

### ISSUE THREAD

**Issue by mqding0564** [tangerzhang/ALLHiC#50]
Hi, I have got a problem when I was running the protocol. I have finished generating the sam file from fq1 and fq2 file, The generated sam file is about 100G, but when I was running the PreprocessSAMs.pl file, it doesn't report any mistake but give no results. The generated bam file is only 1.83K and also the data in sample.bwa_aln.REduced.paired_only.flagstat are zero. Can anybody help me resovle this problem. Thanks!

**Comment by tangerzhang** [comment]
Hi @mqding0564 
Could you please post the command line you used? I assume that the restriction enzyme sites were mis-used.
