### ISSUE TITLE
How can I set up enzyme_sites with enzyme DpnII?

### ISSUE THREAD

**Issue by sunnycqcn** [tangerzhang/ALLHiC#52]
Hello,
My Hi-C data was obtained using enzyme DpnII. However,  AllHiC only has two enzyme options, such as -e : enzyme_sites (HindIII: AAGCTT; MboI: GATC). How can I set up the enzyme sites or I do not need set it?
Thanks,
Fuyou

**Comment by tangerzhang** [comment]
Hi Fuyou,
You can use the restriction sites directly, e.g. -e GATC

**Comment by sunnycqcn** [comment]
Hello, 
Can I use GATC replace MBOI at this step? 
PreprocessSAMs.pl sample.bwa_aln.sam draft.asm.fasta MBOI
Thanks,
Fuyou

**Comment by tangerzhang** [comment]
Yes, as long as this script was downloaded from ALLHiC package rather than LACHESIS package.
