### ISSUE TITLE
some chromosome is too long and  some is too short

### ISSUE THREAD

**Issue by leeun67** [tangerzhang/ALLHiC#55]
hi ,dear author. when i use this tool to assemble my genome.  first,i use the mecat2, and then i use pilion to polish, then use purge-haplotig, finalla use allhic, the survey genome size is 450M, and finally i find some chromosome more than 60M, sonme less than  5M, It is very different to the reference genome ,what should i do to adjust ?Thank you for your attention.

**Comment by tangerzhang** [comment]
Hi @leeun67 
We have discussion regarding this issue with a couple of ALLHiC users. Please see the following link: https://github.com/tangerzhang/ALLHiC/issues/8
Hopefully, this could help you out.
