### ISSUE TITLE
compatibility with DNase HiC

### ISSUE THREAD

**Issue by dabitz** [tangerzhang/ALLHiC#57]
Hi, is ALLHiC compatible with Omni-C libraries? Thanks, André

**Comment by tangerzhang** [comment]
Hi @dabitz ,
It should be compatible with Omni-C libraries if you have already know the restriction sites.
If you have multiple restriction sites, you can follow this guideline to extract reads:
https://github.com/tangerzhang/ALLHiC/issues/31

**Comment by dabitz** [comment]
But OmniC has no specific restriction site nor multiple known sites. It is supposed to cut randomly. So I cannot enter multiple sites because I don't know them...

**Comment by tangerzhang** [comment]
In that case, I am afraid that ALLHiC is not suitable for OmniC :-(

**Comment by dabitz** [comment]
Thanks! It would be nice to have this option in future as OmniC may become very popular...
