### ISSUE TITLE
how can i know the final order of the contigs of one scaffold

### ISSUE THREAD

**Issue by leeun67** [tangerzhang/ALLHiC#59]
嗨，尊敬的作者。我怎样才能得知每一条组装的superscaffold 包含的contig的排列顺序和方向呢？我发现我的组装中有一些错配，所以我能手动讲一个groupx.txt 文件里的contig名称换到另一个groupsx.txt里面，再重新生成tour文件完成组装吗？

**Comment by tangerzhang** [comment]
1. tour文件中的最后一行列出来了染色体的排列顺序和方向
2. 再知道错误的情况下，是可以手工调整groupx.txt文件的。
