### ISSUE TITLE
Some chromosomes of the heat map generated by ALLHiC_plot are blank

### ISSUE THREAD

**Issue by leocha0** [tangerzhang/ALLHiC#60]
Questions are as follows:
![image](https://user-images.githubusercontent.com/70458551/92301432-8ee92b80-ef96-11ea-9675-7906758f43e5.png)
how to solve this problem？ thanks.

**Comment by tangerzhang** [comment]
I assume that the bam file is incomplete. There is a large genomic region that are not covered by any Hi-C read pairs.

**Comment by leocha0** [comment]
ok, Thanks, I will check the bam to find if there are no reads in the regon.

**Comment by dabitz** [comment]
I have got a similar result while trying to plot usig the SALSA agp and I figured out that actually my agp file has some contigs split in contigX_1, contigX_2 that were not in the original bam file... That's why the ALLHiC_plot is not finding these regions.

**Comment by leocha0** [comment]
Yes indeed.  the contigs was missing in the bam. the contigs was exist in the ori_bam 'sample.bwa_aln.bam', but the contigs was missing in the 'sample.bwa_aln.REduced.bam'.  Why is this contig deleted? I checked the contig mapping and there is no problem.  Therefore, the problem should appear in this file ‘PreprocessSAMs.pl’.

**Comment by leocha0** [comment]
I found the reason! The problem was in ‘make_bed_around_RE_site.pl’ script.  The generated bed file is missing the last contig in $assembly. 
for example ：
>tig001
>tig002
>tig003
tig003 was not found in 'assembly.fa.near_GATC.500.bed'. The last contig will never appear in the bed file，it is the processing of the logical relationship that caused the problem.
Therefore,  use the bed file  'near_GATC.500.bed' to filter 'sample.bwa_aln.bam', the last contig was missing, The heat map generated using ALLHiC_plot contains blanks.

**Comment by tangerzhang** [comment]
> I found the reason! The problem was in ‘make_bed_around_RE_site.pl’ script. The generated bed file is missing the last contig in $assembly.
> for example ：
> 
> > tig001
> > tig002
> > tig003
> 
> tig003 was not found in 'assembly.fa.near_GATC.500.bed'. The last contig will never appear in the bed file，it is the logical relationship in the script that caused the problem.
> Therefore, use the bed file 'near_GATC.500.bed' to filter 'sample.bwa_aln.bam', the last contig was missing, The heat map generated using ALLHiC_plot contains blanks.

Hi @leocha0 
Thanks for debugging this problem. The ‘make_bed_around_RE_site.pl’ script was originally from LACHESIS and we did not realize the bug in it. I will fix it once I get a chance. Alternatively, you can use the original bam file (that was not filtered) to plot a heatmap.

**Comment by leocha0** [comment]
@tangerzhang

I added the missing contig infomaton in the bed and re-filtered bam manually, and then the drawing of ALLHiC_plot was ok.

Thanks for providing such excellent software！
