### ISSUE TITLE
How do I set k values, such as the allotetraploid of a Brassica napus (2n=38)

### ISSUE THREAD

**Issue by boweicai** [tangerzhang/ALLHiC#62]
I tried different k values, but the groups that came out were all 23 groups, and the group1 was extremely large, resulting in the final result of Scofflod N50 being extremely large and with only one.
![image](https://user-images.githubusercontent.com/65696529/97109889-dd05ea00-1710-11eb-9c3b-309bae09a538.png)

**Comment by tangerzhang** [comment]
Hi @boweicai 
We have a discussion regarding this issue before following this link (https://github.com/tangerzhang/ALLHiC/issues/8). I hope our previous experience can help you out. If not, please feel free to leave message here. I am open to any question regarding the usage of ALLHiC. Good luck!
