### ISSUE TITLE
get a blank heatmap with ALLHiC_plot and bwa mem data

### ISSUE THREAD

**Issue by Zachary-Wu** [tangerzhang/ALLHiC#64]
Hi,

Thanks for sharing this amazing tool. 

I am building the assemblies according to the homepage pipeline, and the bwa sampe is quite time-consuming, 

so, at the same time, I  tried to use the bwa mem data.  everything looks good, but the heatmap is blank with a matplotlib user warning: "converting a masked element to nan", while I try to plot the heatmap.

I can't find a way to solve this matplotlib problem, Any help would be greatly appreciated.

**Comment by Zachary-Wu** [comment]
I find the reason.

it turns out that I renamed the Hic-reads to its $ac(accession number), so, "read_on_chr" just contains the information of one bwa-mam reads.

BY THE WAY, it is interesting that bwa mem may produce multiple mapped reads. so, I wonder if it may make more sense that we append an index at the end of read_id. Cause, in this case, all of the reads will be calculated in the "ALLHiC_plot" process.

**Comment by tangerzhang** [comment]
Hi @Zachary-Wu 
Glad you have solved this problem.
For the bwa mem, you can extract uniquely mapped reads to avoid multiple alignments.
