### ISSUE TITLE
Problem with polyploid / aneuploid genome

### ISSUE THREAD

**Issue by jhtrujillo** [tangerzhang/ALLHiC#66]

**Comment by jhtrujillo** [comment]
Hi. I just generated the wrk_dir folder, for 10 chromosomes. now I am trying to run the link_superscaffold.pl script, but I have not managed to understand the structure of the code and I have not been able to use it. Could you explain to me a bit, how I could use this script. Besides this, I wonder if to define the order of my groups I also need to do some kind of synth? Thanks a lot.

**Comment by tangerzhang** [comment]
Hi @jhtrujillo ,
The script ```link_superscaffold.pl``` was not well developed and users have to modify it for using at current stage.
I will suggest you can perform a dotplot analysis with a close relative species before next process as the synteny analysis will help you to check the quality of Hi-C scaffolding.
