### ISSUE TITLE
Terminating ... no more ACCEPT

### ISSUE THREAD

**Issue by rapaJiahe** [tangerzhang/ALLHiC#7]
Hi, @tanghaibao and @tangerzhang ,
I used ParaFly to run optimize for ordering and orientation, and from log file, I found a strrange Terminating information.
ESC[32m16:49:58 flipLog | NOTICE ESC[0m FLIPONE (400/562): -420786031.95846 => -420819527.78346 REJECT
ESC[32m16:50:00 flipLog | NOTICE ESC[0m FLIPONE (450/562): -420786031.95846 => -420786031.95846 REJECT
ESC[32m16:50:02 flipLog | NOTICE ESC[0m FLIPONE (500/562): -420786031.95846 => -420786031.95846 REJECT
ESC[32m16:50:04 flipLog | NOTICE ESC[0m FLIPONE (550/562): -420786031.95846 => -420786031.95846 REJECT
ESC[32m16:50:05 flipOne | NOTICE ESC[0m FLIPONE: N_accepts=0 N_rejects=562
ESC[32m16:50:05 Run | NOTICE ESC[0m **Terminating ... no more ACCEPT**

how can i solve this **Terminating ... no more ACCEPT** imformation?

Thank you in advance,

Best
He

**Comment by tanghaibao** [comment]
@rapaJiahe 
This is not an error. It is an indication that the orientation optimization stage is completed. No worries.

Haibao

**Comment by rapaJiahe** [comment]
thank you.
Best
He
