### ISSUE TITLE
fail to download "Tested data"

### ISSUE THREAD

**Issue by zcWang0591** [tangerzhang/ALLHiC#70]
Hi,
I try to download the "Tested data", but fail. It seems that the I can't connect to the ftp server at ftp://59.79.232.12. Is there any other link for downloading "Tested data"? 
Many thanks.

**Comment by tangerzhang** [comment]
I apologize for he inactive link. Please see the link below to download the sample data.
https://pan.baidu.com/s/1caryNh_7tC9GLRdHCWbvDQ
password: hgfl
