### ISSUE TITLE
Closing gaps

### ISSUE THREAD

**Issue by deilepaita** [tangerzhang/ALLHiC#71]
Hi tangerzhang,

Thanks for developing ALLHiC, it is really useful. I am scaffolding a simple diploid genome. After ALLHiC scaffolding, I noticed a number of 100 bp gaps ('NNNNN'). Any recommendation on how to close the gaps?

Thanks!

**Comment by tangerzhang** [comment]
Hi @deilepaita 
To our knowledge, it is not possible to estimate the length of gaps between contigs using only Hi-C data. We therefore use 100 Ns to indicate the gap to link the contigs.
