### ISSUE TITLE
how to convert genome.review.assembly file to .tour file

### ISSUE THREAD

**Issue by jinxin112233** [tangerzhang/ALLHiC#74]
Hi
Under your suggestion, we successfully converted the ALLHIC output files into `.hic` files and `.assembly` files. Then we adjusted the genome with the juicerbox and got better results. But when we use `genome.review.assembly` to get the final adjusted genome file by 3d-DNA, we cannot get the chromosome-level genome `.fa`, and the output file is much smaller. In short, the performance of 3d-DNA is not very good.  Therefore, I have a small idea.  Because ` .tour` file is the input file of ALLHiC_build. And I think that the information contained in the genome.review.assembly and .tour files are similar. Both of them are the key files for elevating the genome to the chromosome level. After we get the `genome.review.assembly` file by juicerbox, can it be converted into a .tour file? Used in ALLHIC for follow-up work.

By the way, I personally prefer the heat map of ALLHIC style.  And we recently test the ALLHIC_corrector. In a word, we think this script can significantly improve  to improve the genome misjoin in 10X HI-C data. We recently test in 122X HI-C data, but the program is still running, and the results have not yet been obtained. You know the `bwa sampe` is very slow. We are not sure whether it will have overcorrect problems in 122X HI-C data.

Best 
JX

**Comment by tangerzhang** [comment]
Hi @jinxin112233 
Thanks for using ALLHiC. 
Would you mind sharing us example(s) of ```genome.review.assembly```? I will check how to convert the format to ```.tour``` files.
Yes, ```bwa sampe``` is pretty slow. You can use ```bwa mem``` instead.

**Comment by jinxin112233** [comment]
Hi
Attached is the `.assembly` file that I output after adjusting with the juicerbox. 
[output.zip](https://github.com/tangerzhang/ALLHiC/files/5799840/output.zip)
I don't know if it can meet your testing needs. 

Thanks for your help.
Best
JX
