### ISSUE TITLE
why list index out of range?

### ISSUE THREAD

**Issue by Ahahaha3** [tangerzhang/ALLHiC#76]
Hi, when i run last step "ALLHiC_plot sample.clean.bam groups.agp chrn.list 500k pdf",  error like:

[17:01:36] Step 1: Get read position based on chromosome
[17:09:27] Step 2: Get chromosome length
[17:09:27] Step 3: Calculating and Drawing heatmap
[17:09:27] Calculating
Traceback (most recent call last):
  File "/data/software/ALLHiC/bin/ALLHiC_plot", line 249, in <module>
    read_count_per_chr, read_count_whole_genome = calc_read_count_per_bin(chr_len_db, chr_order, read_on_chr, bin_size)
  File "/data/software/ALLHiC/bin/ALLHiC_plot", line 112, in calc_read_count_per_bin
    read_count_per_chr[chr1][pos1_index][pos2_index] += 1
IndexError: list index out of range

I have run all the previous programs successfully and get all files. i don't know how to resolve it. Thanks a lot!

**Comment by sc-zhang** [comment]
This problem may be appeared when the length of chromosomes in the chrn.list was not match those in groups.agp. If you are sure that they were matched, maybe you can set the lengths a little longer than the real lengths in the chrn.list, and then run it again.

**Comment by Ahahaha3** [comment]
thanks for your replay. If the length of chromosomes in the chrn.list was not match those in groups.agp, what's the reason?

**Comment by sc-zhang** [comment]
I'm not sure, but if you generate the chrn.list with the groups.asm.fasta, the lengths in chrn.list and groups.agp will not mismatch. Maybe the index out of range is came out with the boundary error in the script, so maybe you can try to edit the chrn.list, and set the lengths longer than the real lengths, than check if it is ok. If so, we will fix this bug later.
