### ISSUE TITLE
make_bed_around_RE_site.pl do not print the last contig.

### ISSUE THREAD

**Issue by mnshgl0110** [tangerzhang/ALLHiC#78]
As the title says, the make_bed_around_RE_site.pl script is bugged and do not print the last print the last contig. This happens because for the final contig the print condition (different contig id) is not satisfied. Adding the print after the while loop fixes the issue.
```
## Paste after the end of while loop

my ( $prev_start, $prev_end ) = (-1,-1);
foreach my $pos ( @motif_positions ) {
    if ( $prev_end == -1 ) {
    $prev_start = $pos;
    $prev_end   = $pos;
    }
    if ( $prev_end + 2*$range < $pos ) {
    $prev_start =         $range if $prev_start < $range;
    $prev_end = $offset - $range if $prev_end > $offset - $range; # prevent overflow past the end of the contig/chromosome
    print BED "$contig_name\t", $prev_start - $range, "\t", $prev_end + $range, "\n";
    $prev_start = $pos;
    }
    #print "pos = $pos\n";
    $prev_end = $pos;
}

# Print the final BED line for this contig/chromosome.
if (@motif_positions) {
    $prev_start =         $range if $prev_start < $range;
    $prev_end = $offset - $range if $prev_end > $offset - $range; # prevent overflow past the end of the contig/chromosome
    print BED "$contig_name\t", $prev_start - $range, "\t", $prev_end + $range, "\n";
}
 
```

**Comment by tangerzhang** [comment]
Hi @mnshgl0110 
Thanks so much for debuging this issue. We will update the code shortly.

**Comment by zengxiaofei** [comment]
These codes may lead to another bug: the RE sites from contigs except for the last one will be printed twice.
Using the script modified by @FlyPythons can solve the problem. [https://github.com/shendurelab/LACHESIS/pull/45](url)
(Notice: The lines that starts with `//` in this script shoud be removed)

**Comment by tangerzhang** [comment]
OK, we will re-write this script and eventually solve the problem when launching ALLHiC2.0. Thanks for mentioning @zengxiaofei

**Comment by zengxiaofei** [comment]
Thanks for your reply.

I find that this script also has a bug :cold_sweat:, which will result in a redundant `>` at the last line of the `POS` file. Line 217-220 in the script could be removed. I could pull a request if necessary.

Xiaofei

**Comment by tangerzhang** [comment]
Hi @zengxiaofei ,
Please revise the script if you think it is a bug:-)
Thanks!
