### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by thomcuddihy** [tangerzhang/ALLHiC#83]
Please provide ALLHiC_Test.zip via a medium that does not require download of client software.

**Comment by tangerzhang** [comment]
Thanks for reminding me. I have uploaded the test data to google drive. Please see the following link for the test data:

https://drive.google.com/file/d/1T58wSCdO4zI5Q4yUs7ggNG7veJTaEBYn/view?usp=sharing

**Comment by thomcuddihy** [comment]
Thanks mate, that's perfect
