### ISSUE TITLE
How can I use ALLHiC with multiple Hi-C libraries?

### ISSUE THREAD

**Issue by cgy0627** [tangerzhang/ALLHiC#88]
Hello,

I have five paired sets of Hi-C data that I would like to use for scaffolding.
Should I use tools like picard MergeSamFiles to merge the five bam file outputs before moving on with further steps?

Thank you.

**Comment by xinghua1001** [comment]
I have the same question. I just use `cat` to combine all the fastq.gz files. I am wondering if I am right

**Comment by tangerzhang** [comment]
Hi @cgy0627 , I usually use ```samtools merge``` to merge all of the bam files into one.
@xinghua1001 , cat the fastq.gz files should be OK.

**Comment by cgy0627** [comment]
Thank you!
