### ISSUE TITLE
Format Allele.ctg.table

### ISSUE THREAD

**Issue by diriano** [tangerzhang/ALLHiC#9]
Could you please provide a full description of Allele.ctg.table?

I have assembled a highly polymorphic diploid species, and used haploMerger2 to separate the two haplotypes. I have a file that tracks which contigs are alternative versions of each other. I think I can use that to generate Allele.ctg.table, I just need a good description of this file. Will appreciate your help. Thanks.

**Comment by tangerzhang** [comment]
Yes, you can use haploMerger2 or other similar programs like  purge_haplotigs to generate the Allele.ctg.table.
Format of Allele.ctg.table:
The first two columns are the chromosome ID and position of reference genome. (You can leave them with NA if you are not using reference genome to generate the Allele.ctg.table)
The 3rd to Nth columns are allelic contigs we identified. Prune step will remove the Hi-C linked reads between allelic contigs.
Hope this is useful!

**Comment by diriano** [comment]
Thanks for your reply.
One further question, what about contigs that do not have allelic counterparts, i.e., homozygous contigs. How should they appear in Allele.ctg.table?
Thanks

**Comment by tangerzhang** [comment]
Hi, you can just leave them as a singleton in the Allele.ctg.table.
Alternatively, I am thinking may be you can keep them away from pruning and rescue them in the ALLHiC rescue step.
Let me do some test in the following days and I will keep you posted.

**Comment by diriano** [comment]
OK. Will be eagerly awaiting for your test results.

**Comment by christinawu2008** [comment]
Any updates on this one? thank you!

**Comment by tangerzhang** [comment]
Sorry that this take a long time. I have some updates for the Allele.ctg.table. Briefly,
(1) leaving the homozygous contigs without counterparts away from the Allele.ctg.table will not affect the final results. 
(2) If there is no closely related species available, a fairly distant species can be used as a reference to identify allelic contigs if they locally maintain good synteny. This will not increase mis-assembly at least for my simulation data.
(3) Whole genome alignment based methods, such as purge_haplotigs, will greatly increase error rate of incorrectly clustered contigs and are not best choice to identify allelic contigs.
I will keep this issue open for a while. Feel free to post any question related this.

**Comment by diriano** [comment]
Ok. Thanks for the update.
So, would haplomerger2 fall in the same category as purge_haplotigs?

**Comment by ardy20** [comment]
Hi 

I am trying to create a Allele.ctg.table but not sure how to prepare it. In the example provided:

$ blastn -query rice.cds -db Bd.cds -out rice_vs_Sb.blast.out -evalue 0.001 -outfmt 6 -num_threads 4 -num_alignments 1

Is rice.cd the target and Bd.cds the closely related? Should we creat a database from Bd.cds first?

Could you please explain this a bit more: Note: Please modify cds name before running BLAST. The cds name should be same with gene name present in GFF3

I also do not get how to modify cds name before blast! Do you mean files name or header of genes in cds? Please briefly explain how to do that?

Should the cds headers in rice.cds and Bd.cds be the same? If yes, how to change?

**Comment by tangerzhang** [comment]
> Hi
> 
> I am trying to create a Allele.ctg.table but not sure how to prepare it. In the example provided:
> 
> $ blastn -query rice.cds -db Bd.cds -out rice_vs_Sb.blast.out -evalue 0.001 -outfmt 6 -num_threads 4 -num_alignments 1
> 
> Is rice.cd the target and Bd.cds the closely related? Should we creat a database from Bd.cds first?
> 
> Could you please explain this a bit more: Note: Please modify cds name before running BLAST. The cds name should be same with gene name present in GFF3
> 
> I also do not get how to modify cds name before blast! Do you mean files name or header of genes in cds? Please briefly explain how to do that?
> 
> Should the cds headers in rice.cds and Bd.cds be the same? If yes, how to change?

Hi @ardy20 
Can you use the gmap-based approach to identify allelic table following guideline from this link: https://github.com/tangerzhang/ALLHiC/issues/16
This is more efficient than blast based approach.
