### ISSUE TITLE
the problem of partiition

### ISSUE THREAD

**Issue by phil622** [tangerzhang/ALLHiC#95]
Hi,
I skip the prunning part and when i use this command: ALLHiC_partition -b sample.clean.bam -r draft.asm.fasta -e GATC -k 9
the result give me 235 groups. I only set up 9 groups ,why it give me so many groups?

**Comment by tangerzhang** [comment]
Hi @phil622 
It happens when the Hi-C is far from high-quality. Did you use HiC-Pro to check the unique mapping and valid rate?

**Comment by phil622** [comment]
not yet. so i should check my Hi-C date throuth HiC-Pro first?

**Comment by phil622** [comment]
not yet. so i should check my Hi-C data throuth HiC-Pro first?

**Comment by tangerzhang** [comment]
Hi @phil622 
Yes, I think the hic quality is likely an issue resulting in this situation.

**Comment by phil622** [comment]
hello
I have test my data through HiC-Pro, and the mapping rate is 80% almost, so i think my data is high-quality
now i am thinking if it is the reason for this problem that i skip the pruning part, my data is a Allotetraploid
thank you for your help

**Comment by phil622** [comment]
but my reported-pairs rate only 34.8%, so i don't know if my data is high-quality.

**Comment by tangerzhang** [comment]
How about the valid rate?

**Comment by phil622** [comment]
the valid pairs rate are 70%, but the cis
 long rate are only 20%

**Comment by phil622** [comment]
Now, I also do the pruning part, but it still have the same problem in the partition part.
How can i do for that.
Thanks.

**Comment by phil622** [comment]
![1627963771(1)](https://user-images.githubusercontent.com/79780714/127956347-2a5157d7-8e2c-4b4b-8d39-dbca881eb2f2.png)

**Comment by phil622** [comment]
There are my HiC-Pro results.
![1627963962](https://user-images.githubusercontent.com/79780714/127956918-b6b4c83e-bfc0-4351-8f90-b33df2cdd052.png)
![1627963976(1)](https://user-images.githubusercontent.com/79780714/127956932-f9dd8310-9474-40bf-9f15-c118bdb61421.png)
![1627963989(1)](https://user-images.githubusercontent.com/79780714/127956938-24620545-2467-442d-9fcc-870d0a0d0d2f.png)

**Comment by tangerzhang** [comment]
Hi @phil622 
Even though the valid rate is 70%, I still have doubt that the valid reads are not enough to link the contigs into chromosomes. I would suggest to check the coverage of the Hi-C sequencing data and also how many reads are left for scaffolding after a series of filtering steps.
