### ISSUE TITLE
How to anchor two haplotypes of simple diploid genome?

### ISSUE THREAD

**Issue by xiekunwhy** [tangerzhang/ALLHiC#99]
Hi,

I got 2 haplotypes of a simple genome using hifiasm(https://github.com/chhylp123/hifiasm) with HiC data, and I want to know how to anchor these two haplotypes to chromosome-level using allhic. 1) To anchor them separately or 2) cat them together and anchor  them to 2n chromomes?

Best,
Kun

**Comment by tangerzhang** [comment]
Anchoring them separately would be much easier than the second approach.

**Comment by Tierhon** [comment]
I'm sorry for replying to a closed thread, but I basically have the question and would like to ask a couple of follow-up questions. 

Sometimes, the two haplotypes might have large differences, inversions for instance, where actually splitting the HiC data in some way into the two haplotypes would be beneficial. If one concatenates the two haplotypes, and then map HiC reads to the diploid (or dual) assembly, then some HiC reads would map to each haplotype, but maybe not enough for scaffolding? With more and more assemblers outputting diploid or dual assemblies, it would be nice to have a haplotype-aware way of scaffolding them.

**Comment by Wenwen012345** [comment]
> Anchoring them separately would be much easier than the second approach.

Hello, @tangerzhang I would like to ask by the way.  It seems to be full of chimeric contigs in my case.  There is an extra large chromosome being built.  Is it because of the &quot;anchor together (2n chromosomes)&quot; method used?
